-- access_counter definition

-- Drop table

-- DROP TABLE access_counter;

CREATE TABLE access_counter (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NOT NULL,
	created_date timestamp NOT NULL,
	last_modified_by varchar(255) NOT NULL,
	last_modified_date timestamp NOT NULL,
	"version" int8 NOT NULL,
	count int8 NULL,
	status varchar(255) NOT NULL,
	url varchar(1000) NULL,
	CONSTRAINT access_counter_idx1 UNIQUE (url),
	CONSTRAINT access_counter_pkey PRIMARY KEY (id)
);


-- account definition

-- Drop table

-- DROP TABLE account;

CREATE TABLE account (
	username varchar(255) NOT NULL,
	created_by varchar(255) NOT NULL,
	created_date timestamp NOT NULL,
	last_modified_by varchar(255) NOT NULL,
	last_modified_date timestamp NOT NULL,
	"version" int8 NOT NULL,
	allowed_ip varchar(255) NULL,
	api_key varchar(255) NULL,
	department varchar(255) NULL,
	email varchar(255) NULL,
	first_name varchar(255) NULL,
	image_uuid varchar(255) NULL,
	last_name varchar(255) NULL,
	"password" varchar(255) NULL,
	profile varchar(1000) NULL,
	status varchar(255) NULL,
	url varchar(255) NULL,
	CONSTRAINT account_idx1 UNIQUE (api_key),
	CONSTRAINT account_pkey PRIMARY KEY (username)
);


-- "document" definition

-- Drop table

-- DROP TABLE "document";

CREATE TABLE "document" (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NOT NULL,
	created_date timestamp NOT NULL,
	last_modified_by varchar(255) NOT NULL,
	last_modified_date timestamp NOT NULL,
	"version" int8 NOT NULL,
	announce_date date NULL,
	body text NULL,
	charge_person_for_creation varchar(255) NULL,
	charge_person_for_publish varchar(255) NULL,
	customer_public varchar(255) NOT NULL,
	department_for_creation varchar(255) NULL,
	department_for_publish varchar(255) NULL,
	doc_category1 varchar(255) NULL,
	doc_category2 varchar(255) NULL,
	doc_service1 varchar(255) NULL,
	doc_service2 varchar(255) NULL,
	doc_service3 varchar(255) NULL,
	document_number varchar(255) NULL,
	intended_reader varchar(255) NULL,
	invalidation_date date NULL,
	last_revised_date date NULL,
	public_scope varchar(255) NOT NULL,
	published_date date NULL,
	reason_for_change varchar(255) NULL,
	remark varchar(255) NULL,
	responsible_person_for_publish varchar(255) NULL,
	save_revision bool NOT NULL,
	status varchar(255) NOT NULL,
	title varchar(255) NULL,
	use_stage_list varchar(255) NULL,
	version_number varchar(255) NULL,
	CONSTRAINT document_pkey PRIMARY KEY (id)
);


-- document_access definition

-- Drop table

-- DROP TABLE document_access;

CREATE TABLE document_access (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	access_date date NULL,
	document_id int8 NULL,
	last_modified_date timestamp NOT NULL,
	username varchar(255) NULL,
	CONSTRAINT data_access_idx1 UNIQUE (access_date, username, document_id),
	CONSTRAINT document_access_pkey PRIMARY KEY (id)
);


-- document_index definition

-- Drop table

-- DROP TABLE document_index;

CREATE TABLE document_index (
	id int8 NOT NULL,
	"no" int4 NOT NULL,
	announce_date varchar(255) NULL,
	body text NULL,
	body_plain text NULL,
	charge_person_for_creation varchar(255) NULL,
	charge_person_for_publish varchar(255) NULL,
	"content" text NULL,
	created_by varchar(255) NOT NULL,
	created_date varchar(255) NOT NULL,
	customer_public varchar(255) NULL,
	department_for_creation varchar(255) NULL,
	department_for_publish varchar(255) NULL,
	doc_category1 varchar(255) NULL,
	doc_category2 varchar(255) NULL,
	doc_service1 varchar(255) NULL,
	doc_service2 varchar(255) NULL,
	doc_service3 varchar(255) NULL,
	document_number varchar(255) NULL,
	file_memo varchar(255) NULL,
	file_uuid varchar(255) NULL,
	invalidation_date varchar(255) NULL,
	last_modified_by varchar(255) NOT NULL,
	last_modified_date timestamp NOT NULL,
	last_modified_date_str varchar(255) NOT NULL,
	last_revised_date varchar(255) NULL,
	pdf_uuid varchar(255) NULL,
	public_scope varchar(255) NULL,
	published_date varchar(255) NULL,
	reason_for_change varchar(255) NULL,
	remark varchar(255) NULL,
	responsible_person_for_publish varchar(255) NULL,
	save_revision bool NOT NULL,
	status varchar(255) NULL,
	title varchar(255) NULL,
	"type" varchar(255) NULL,
	"version" int8 NOT NULL,
	version_number varchar(255) NULL,
	CONSTRAINT document_index_pkey PRIMARY KEY (id, no)
);


-- document_max_rev definition

-- Drop table

-- DROP TABLE document_max_rev;

CREATE TABLE document_max_rev (
	id int8 NOT NULL,
	rid int8 NOT NULL,
	CONSTRAINT document_max_rev_pkey PRIMARY KEY (id)
);


-- document_revision definition

-- Drop table

-- DROP TABLE document_revision;

CREATE TABLE document_revision (
	rid int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NULL,
	created_date timestamp NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp NULL,
	rev_type int4 NOT NULL,
	"version" int8 NOT NULL,
	announce_date date NULL,
	body text NULL,
	charge_person_for_creation varchar(255) NULL,
	charge_person_for_publish varchar(255) NULL,
	customer_public varchar(255) NULL,
	department_for_creation varchar(255) NULL,
	department_for_publish varchar(255) NULL,
	doc_category1 varchar(255) NULL,
	doc_category2 varchar(255) NULL,
	doc_service1 varchar(255) NULL,
	doc_service2 varchar(255) NULL,
	doc_service3 varchar(255) NULL,
	document_number varchar(255) NULL,
	id int8 NULL,
	intended_reader varchar(255) NULL,
	invalidation_date date NULL,
	last_revised_date date NULL,
	public_scope varchar(255) NULL,
	published_date date NULL,
	reason_for_change varchar(255) NULL,
	remark varchar(255) NULL,
	responsible_person_for_publish varchar(255) NULL,
	save_revision bool NOT NULL,
	status varchar(255) NULL,
	title varchar(255) NULL,
	version_number varchar(255) NULL,
	CONSTRAINT document_revision_pkey PRIMARY KEY (rid)
);


-- email_change_request definition

-- Drop table

-- DROP TABLE email_change_request;

CREATE TABLE email_change_request (
	"token" varchar(255) NOT NULL,
	expiry_date timestamp NULL,
	new_mail varchar(255) NULL,
	secret varchar(255) NULL,
	username varchar(255) NULL,
	CONSTRAINT email_change_request_pkey PRIMARY KEY (token)
);


-- failed_authentication definition

-- Drop table

-- DROP TABLE failed_authentication;

CREATE TABLE failed_authentication (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	authentication_timestamp timestamp NULL,
	username varchar(255) NULL,
	CONSTRAINT failed_authentication_pkey PRIMARY KEY (id)
);


-- failed_email_change_request definition

-- Drop table

-- DROP TABLE failed_email_change_request;

CREATE TABLE failed_email_change_request (
	attempt_date timestamp NOT NULL,
	"token" varchar(255) NOT NULL,
	CONSTRAINT failed_email_change_request_pkey PRIMARY KEY (attempt_date, token)
);


-- failed_password_reissue definition

-- Drop table

-- DROP TABLE failed_password_reissue;

CREATE TABLE failed_password_reissue (
	attempt_date timestamp NOT NULL,
	"token" varchar(255) NOT NULL,
	created_by varchar(255) NOT NULL,
	CONSTRAINT failed_password_reissue_pkey PRIMARY KEY (attempt_date, token)
);


-- file_managed definition

-- Drop table

-- DROP TABLE file_managed;

CREATE TABLE file_managed (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NOT NULL,
	created_date timestamp NOT NULL,
	last_modified_by varchar(255) NOT NULL,
	last_modified_date timestamp NOT NULL,
	"version" int8 NOT NULL,
	file_mime varchar(255) NULL,
	file_size int8 NULL,
	file_type varchar(255) NULL,
	original_filename varchar(255) NULL,
	status varchar(255) NULL DEFAULT '0'::character varying,
	uri varchar(255) NULL,
	uuid varchar(255) NULL,
	CONSTRAINT file_managed_idx1 UNIQUE (uuid),
	CONSTRAINT file_managed_idx2 UNIQUE (uri),
	CONSTRAINT file_managed_pkey PRIMARY KEY (id)
);


-- mail_send_history definition

-- Drop table

-- DROP TABLE mail_send_history;

CREATE TABLE mail_send_history (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	body varchar(255) NULL,
	created_by varchar(255) NULL,
	email varchar(255) NULL,
	username varchar(255) NULL,
	send_time timestamp NULL,
	subject varchar(255) NULL,
	CONSTRAINT mail_send_history_pkey PRIMARY KEY (id)
);


-- password_history definition

-- Drop table

-- DROP TABLE password_history;

CREATE TABLE password_history (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NOT NULL,
	"password" varchar(255) NULL,
	use_from timestamp NULL,
	username varchar(255) NULL,
	CONSTRAINT password_history_pkey PRIMARY KEY (id)
);


-- password_reissue_info definition

-- Drop table

-- DROP TABLE password_reissue_info;

CREATE TABLE password_reissue_info (
	"token" varchar(255) NOT NULL,
	created_by varchar(255) NOT NULL,
	expiry_date timestamp NULL,
	secret varchar(255) NULL,
	username varchar(255) NULL,
	CONSTRAINT password_reissue_info_pkey PRIMARY KEY (token)
);


-- permission_role definition

-- Drop table

-- DROP TABLE permission_role;

CREATE TABLE permission_role (
	"permission" varchar(255) NOT NULL,
	"role" varchar(255) NOT NULL,
	CONSTRAINT permission_role_pkey PRIMARY KEY (permission, role)
);


-- person definition

-- Drop table

-- DROP TABLE person;

CREATE TABLE person (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NOT NULL,
	created_date timestamp NOT NULL,
	last_modified_by varchar(255) NOT NULL,
	last_modified_date timestamp NOT NULL,
	"version" int8 NOT NULL,
	age int4 NULL,
	attached_file01uuid varchar(255) NULL,
	code varchar(255) NULL,
	"content" text NULL,
	name varchar(255) NULL,
	status varchar(255) NOT NULL,
	memo varchar(255) NULL,
	CONSTRAINT person_pkey PRIMARY KEY (id)
);


-- select_max_rev definition

-- Drop table

-- DROP TABLE select_max_rev;

CREATE TABLE select_max_rev (
	id int8 NOT NULL,
	rid int8 NOT NULL,
	CONSTRAINT select_max_rev_pkey PRIMARY KEY (id)
);


-- select_revision definition

-- Drop table

-- DROP TABLE select_revision;

CREATE TABLE select_revision (
	rid int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NULL,
	created_date timestamp NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp NULL,
	rev_type int4 NOT NULL,
	"version" int8 NOT NULL,
	id int8 NOT NULL,
	select01 varchar(255) NOT NULL,
	select02 varchar(255) NOT NULL,
	status varchar(255) NOT NULL,
	CONSTRAINT select_revision_pkey PRIMARY KEY (rid)
);


-- select_table definition

-- Drop table

-- DROP TABLE select_table;

CREATE TABLE select_table (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NOT NULL,
	created_date timestamp NOT NULL,
	last_modified_by varchar(255) NOT NULL,
	last_modified_date timestamp NOT NULL,
	"version" int8 NOT NULL,
	select01 varchar(255) NULL,
	select02 varchar(255) NULL,
	status varchar(255) NOT NULL,
	CONSTRAINT select_table_pkey PRIMARY KEY (id)
);


-- simple_entity definition

-- Drop table

-- DROP TABLE simple_entity;

CREATE TABLE simple_entity (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NOT NULL,
	created_date timestamp NOT NULL,
	last_modified_by varchar(255) NOT NULL,
	last_modified_date timestamp NOT NULL,
	"version" int8 NOT NULL,
	attached_file01uuid varchar(255) NULL,
	checkbox01 varchar(255) NULL,
	combobox01 varchar(255) NULL,
	combobox02 varchar(255) NULL,
	date01 date NULL,
	datetime01 timestamp NULL,
	radio01 bool NULL,
	radio02 varchar(255) NULL,
	select01 varchar(255) NULL,
	select03 varchar(255) NULL,
	status varchar(255) NOT NULL,
	text01 varchar(255) NULL,
	text02 int4 NULL,
	text03 float4 NULL,
	text04 int2 NULL,
	textarea01 varchar(255) NULL,
	CONSTRAINT simple_entity_pkey PRIMARY KEY (id)
);


-- simple_entity_max_rev definition

-- Drop table

-- DROP TABLE simple_entity_max_rev;

CREATE TABLE simple_entity_max_rev (
	id int8 NOT NULL,
	rid int8 NOT NULL,
	CONSTRAINT simple_entity_max_rev_pkey PRIMARY KEY (id)
);


-- simple_entity_revision definition

-- Drop table

-- DROP TABLE simple_entity_revision;

CREATE TABLE simple_entity_revision (
	rid int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NULL,
	created_date timestamp NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp NULL,
	rev_type int4 NOT NULL,
	"version" int8 NOT NULL,
	attached_file01uuid varchar(255) NULL,
	checkbox01 varchar(255) NULL,
	combobox01 varchar(255) NULL,
	combobox02 varchar(255) NULL,
	date01 date NULL,
	datetime01 timestamp NULL,
	id int8 NOT NULL,
	radio01 bool NULL,
	radio02 varchar(255) NULL,
	select01 varchar(255) NULL,
	select03 varchar(255) NULL,
	status varchar(255) NOT NULL,
	text01 varchar(255) NULL,
	text02 int4 NULL,
	text03 float4 NULL,
	text04 bool NULL,
	textarea01 varchar(255) NULL,
	CONSTRAINT simple_entity_revision_pkey PRIMARY KEY (rid)
);


-- successful_authentication definition

-- Drop table

-- DROP TABLE successful_authentication;

CREATE TABLE successful_authentication (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	authentication_timestamp timestamp NULL,
	created_by varchar(255) NOT NULL,
	username varchar(255) NULL,
	CONSTRAINT successful_authentication_pkey PRIMARY KEY (id)
);


-- temp_file definition

-- Drop table

-- DROP TABLE temp_file;

CREATE TABLE temp_file (
	id varchar(255) NOT NULL,
	body oid NULL,
	original_name varchar(255) NULL,
	uploaded_date timestamp NULL,
	CONSTRAINT temp_file_pkey PRIMARY KEY (id)
);


-- variable definition

-- Drop table

-- DROP TABLE variable;

CREATE TABLE variable (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NOT NULL,
	created_date timestamp NOT NULL,
	last_modified_by varchar(255) NOT NULL,
	last_modified_date timestamp NOT NULL,
	"version" int8 NOT NULL,
	code varchar(255) NOT NULL,
	date1 date NULL,
	date2 date NULL,
	date3 date NULL,
	date4 date NULL,
	date5 date NULL,
	file1uuid varchar(255) NULL,
	remark varchar(255) NULL,
	status varchar(255) NULL,
	textarea text NULL,
	"type" varchar(255) NOT NULL,
	valint1 int4 NULL,
	valint2 int4 NULL,
	valint3 int4 NULL,
	valint4 int4 NULL,
	valint5 int4 NULL,
	value1 varchar(255) NULL,
	value10 varchar(255) NULL,
	value2 varchar(255) NULL,
	value3 varchar(255) NULL,
	value4 varchar(255) NULL,
	value5 varchar(255) NULL,
	value6 varchar(255) NULL,
	value7 varchar(255) NULL,
	value8 varchar(255) NULL,
	value9 varchar(255) NULL,
	CONSTRAINT variable_idx1 UNIQUE (type, code),
	CONSTRAINT variable_pkey PRIMARY KEY (id)
);


-- workflow definition

-- Drop table

-- DROP TABLE workflow;

CREATE TABLE workflow (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NOT NULL,
	created_date timestamp NOT NULL,
	last_modified_by varchar(255) NOT NULL,
	last_modified_date timestamp NOT NULL,
	"version" int8 NOT NULL,
	employee_id int8 NOT NULL,
	entity_id int8 NOT NULL,
	entity_type varchar(255) NOT NULL,
	step_no int4 NOT NULL,
	step_status int4 NOT NULL,
	weight int4 NOT NULL DEFAULT 0,
	CONSTRAINT workflow_idx1 UNIQUE (entity_type, entity_id, step_no, employee_id),
	CONSTRAINT workflow_pkey PRIMARY KEY (id)
);


-- account_roles definition

-- Drop table

-- DROP TABLE account_roles;

CREATE TABLE account_roles (
	account_username varchar(255) NOT NULL,
	roles varchar(255) NULL,
	CONSTRAINT fksa8fblleof2c8aqce4x3n0yy5 FOREIGN KEY (account_username) REFERENCES account(username)
);


-- document_files definition

-- Drop table

-- DROP TABLE document_files;

CREATE TABLE document_files (
	document_id int8 NOT NULL,
	file_uuid varchar(255) NULL,
	file_memo varchar(255) NULL,
	pdf_uuid varchar(255) NULL,
	"type" varchar(255) NULL,
	files_order int4 NOT NULL,
	CONSTRAINT document_files_pkey PRIMARY KEY (document_id, files_order),
	CONSTRAINT fk1b767qp1gkma8nuq8en8oygen FOREIGN KEY (document_id) REFERENCES "document"(id)
);


-- document_index_use_stage definition

-- Drop table

-- DROP TABLE document_index_use_stage;

CREATE TABLE document_index_use_stage (
	document_index_id int8 NOT NULL,
	document_index_no int4 NOT NULL,
	use_stage varchar(255) NULL,
	CONSTRAINT fkleu7m83uqab8mmh7ed4odv9qj FOREIGN KEY (document_index_id,document_index_no) REFERENCES document_index(id,"no")
);


-- document_revision_files definition

-- Drop table

-- DROP TABLE document_revision_files;

CREATE TABLE document_revision_files (
	document_revision_rid int8 NOT NULL,
	file_uuid varchar(255) NULL,
	file_memo varchar(255) NULL,
	pdf_uuid varchar(255) NULL,
	"type" varchar(255) NULL,
	CONSTRAINT fkfb6pqvb7xwca2c56ubwpjmt8i FOREIGN KEY (document_revision_rid) REFERENCES document_revision(rid)
);


-- document_revision_use_stage definition

-- Drop table

-- DROP TABLE document_revision_use_stage;

CREATE TABLE document_revision_use_stage (
	document_revision_rid int8 NOT NULL,
	use_stage varchar(255) NULL,
	CONSTRAINT fkeadlw1pajfi4lne0evc3edewq FOREIGN KEY (document_revision_rid) REFERENCES document_revision(rid)
);


-- document_use_stage definition

-- Drop table

-- DROP TABLE document_use_stage;

CREATE TABLE document_use_stage (
	document_id int8 NOT NULL,
	use_stage varchar(255) NULL,
	CONSTRAINT fk6e2wqg1fhhig392vq9edjr0g7 FOREIGN KEY (document_id) REFERENCES "document"(id)
);


-- simple_entity_checkbox02 definition

-- Drop table

-- DROP TABLE simple_entity_checkbox02;

CREATE TABLE simple_entity_checkbox02 (
	simple_entity_id int8 NOT NULL,
	checkbox02 varchar(255) NULL,
	CONSTRAINT fkrmv44v1sgjx7l30nrw3erf0re FOREIGN KEY (simple_entity_id) REFERENCES simple_entity(id)
);


-- simple_entity_combobox03 definition

-- Drop table

-- DROP TABLE simple_entity_combobox03;

CREATE TABLE simple_entity_combobox03 (
	simple_entity_id int8 NOT NULL,
	combobox03 varchar(255) NULL,
	CONSTRAINT fkilbmxju7vidne5iwurrto4fn2 FOREIGN KEY (simple_entity_id) REFERENCES simple_entity(id)
);


-- simple_entity_line_items definition

-- Drop table

-- DROP TABLE simple_entity_line_items;

CREATE TABLE simple_entity_line_items (
	simple_entity_id int8 NOT NULL,
	item_name varchar(255) NULL,
	item_no int8 NULL,
	item_number int4 NULL,
	unit_prise int4 NULL,
	CONSTRAINT fk9p2ff74vnn6dpq4gu0edaw9iw FOREIGN KEY (simple_entity_id) REFERENCES simple_entity(id)
);


-- simple_entity_revision_checkbox02 definition

-- Drop table

-- DROP TABLE simple_entity_revision_checkbox02;

CREATE TABLE simple_entity_revision_checkbox02 (
	simple_entity_revision_rid int8 NOT NULL,
	checkbox02 varchar(255) NULL,
	CONSTRAINT fkjj2hm7b5c3xv6foi51n20wy06 FOREIGN KEY (simple_entity_revision_rid) REFERENCES simple_entity_revision(rid)
);


-- simple_entity_revision_combobox03 definition

-- Drop table

-- DROP TABLE simple_entity_revision_combobox03;

CREATE TABLE simple_entity_revision_combobox03 (
	simple_entity_revision_rid int8 NOT NULL,
	combobox03 varchar(255) NULL,
	CONSTRAINT fkos8picdxl023m189uqeyut1yr FOREIGN KEY (simple_entity_revision_rid) REFERENCES simple_entity_revision(rid)
);


-- simple_entity_revision_line_items definition

-- Drop table

-- DROP TABLE simple_entity_revision_line_items;

CREATE TABLE simple_entity_revision_line_items (
	simple_entity_revision_rid int8 NOT NULL,
	item_name varchar(255) NULL,
	item_no int8 NULL,
	item_number int4 NULL,
	unit_prise int4 NULL,
	CONSTRAINT fkm74nkmtffqq3pnaffiwumrk5h FOREIGN KEY (simple_entity_revision_rid) REFERENCES simple_entity_revision(rid)
);


-- simple_entity_revision_select02 definition

-- Drop table

-- DROP TABLE simple_entity_revision_select02;

CREATE TABLE simple_entity_revision_select02 (
	simple_entity_revision_rid int8 NOT NULL,
	select02 varchar(255) NULL,
	CONSTRAINT fks6pq89gb97b3v5bdebnkp2dda FOREIGN KEY (simple_entity_revision_rid) REFERENCES simple_entity_revision(rid)
);


-- simple_entity_revision_select04 definition

-- Drop table

-- DROP TABLE simple_entity_revision_select04;

CREATE TABLE simple_entity_revision_select04 (
	simple_entity_revision_rid int8 NOT NULL,
	select04 varchar(255) NULL,
	CONSTRAINT fkoxks4uuxq3yxse7iydlvfvd5w FOREIGN KEY (simple_entity_revision_rid) REFERENCES simple_entity_revision(rid)
);


-- simple_entity_revision_text05 definition

-- Drop table

-- DROP TABLE simple_entity_revision_text05;

CREATE TABLE simple_entity_revision_text05 (
	simple_entity_revision_rid int8 NOT NULL,
	text05 varchar(255) NULL,
	CONSTRAINT fkkmxcf81bd8vgmasf649wlg1ux FOREIGN KEY (simple_entity_revision_rid) REFERENCES simple_entity_revision(rid)
);


-- simple_entity_select02 definition

-- Drop table

-- DROP TABLE simple_entity_select02;

CREATE TABLE simple_entity_select02 (
	simple_entity_id int8 NOT NULL,
	select02 varchar(255) NULL,
	CONSTRAINT fk221mpw54qo7ostpnqtecb4jv5 FOREIGN KEY (simple_entity_id) REFERENCES simple_entity(id)
);


-- simple_entity_select04 definition

-- Drop table

-- DROP TABLE simple_entity_select04;

CREATE TABLE simple_entity_select04 (
	simple_entity_id int8 NOT NULL,
	select04 varchar(255) NULL,
	CONSTRAINT fkg0f3xp1brlfmr8etthrvaq2el FOREIGN KEY (simple_entity_id) REFERENCES simple_entity(id)
);


-- simple_entity_text05 definition

-- Drop table

-- DROP TABLE simple_entity_text05;

CREATE TABLE simple_entity_text05 (
	simple_entity_id int8 NOT NULL,
	text05 varchar(255) NULL,
	CONSTRAINT fkeaiyyh79glf138bqsneolhd9k FOREIGN KEY (simple_entity_id) REFERENCES simple_entity(id)
);