package jp.co.stnet.cms.base.domain.model.mbg;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.time.LocalDateTime;
import jp.co.stnet.cms.base.domain.model.KeyInterface;
import jp.co.stnet.cms.base.domain.model.StatusInterface;
import jp.co.stnet.cms.base.domain.model.VersionInterface;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * Database Table Remarks:
 *   アカウント
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table account
 */
@Data
@EqualsAndHashCode
@ToString
public class Account implements Serializable, KeyInterface<String>, VersionInterface, StatusInterface {
    /**
     * Database Column Remarks:
     *   ユーザID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   ステータス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     * Database Column Remarks:
     *   バージョン
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.version
     *
     * @mbg.generated
     */
    private Long version;

    /**
     * Database Column Remarks:
     *   作成者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     * Database Column Remarks:
     *   作成日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.created_date
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy/MM/dd HH:mm:ss")
    private LocalDateTime createdDate;

    /**
     * Database Column Remarks:
     *   最終更新者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.last_modified_by
     *
     * @mbg.generated
     */
    private String lastModifiedBy;

    /**
     * Database Column Remarks:
     *   最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.last_modified_date
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy/MM/dd HH:mm:ss")
    private LocalDateTime lastModifiedDate;

    /**
     * Database Column Remarks:
     *   パスワード
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.first_name
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     * Database Column Remarks:
     *   姓
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.last_name
     *
     * @mbg.generated
     */
    private String lastName;

    /**
     * Database Column Remarks:
     *   メールアドレス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   所属部門
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.department
     *
     * @mbg.generated
     */
    private String department;

    /**
     * Database Column Remarks:
     *   URL
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * Database Column Remarks:
     *   プロフィール
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.profile
     *
     * @mbg.generated
     */
    private String profile;

    /**
     * Database Column Remarks:
     *   ログイン許可IPアドレス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.allowed_ip
     *
     * @mbg.generated
     */
    private String allowedIp;

    /**
     * Database Column Remarks:
     *   API KEY
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.api_key
     *
     * @mbg.generated
     */
    private String apiKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table account
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return username;
    }
}