package jp.co.stnet.cms.base.domain.model.mbg;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.time.LocalDateTime;
import jp.co.stnet.cms.base.domain.model.KeyInterface;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

/**
 * Database Table Remarks:
 *   メールアドレス変更要求
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_email_change_request
 */
@Data
@SuperBuilder
@EqualsAndHashCode
@AllArgsConstructor
@ToString
@NoArgsConstructor
public class EmailChangeRequest implements Serializable, KeyInterface<String> {
    /**
     * Database Column Remarks:
     *   トークン
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email_change_request.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     * Database Column Remarks:
     *   ユーザid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email_change_request.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   暗証番号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email_change_request.secret
     *
     * @mbg.generated
     */
    private String secret;

    /**
     * Database Column Remarks:
     *   新メールアドレス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email_change_request.new_mail
     *
     * @mbg.generated
     */
    private String newMail;

    /**
     * Database Column Remarks:
     *   有効期限
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_email_change_request.expiry_date
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy/MM/dd HH:mm:ss")
    private LocalDateTime expiryDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_email_change_request
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return token;
    }
}