package jp.co.stnet.cms.base.domain.model.mbg;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import jp.co.stnet.cms.base.domain.model.KeyInterface;
import jp.co.stnet.cms.base.domain.model.mbg.FailedAuthenticationKey;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * Database Table Remarks:
 *   認証失敗履歴
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms.failed_authentication
 */
@Data
@EqualsAndHashCode(callSuper = true)
@ToString(callSuper = true)
public class FailedAuthentication extends FailedAuthenticationKey implements Serializable, KeyInterface<FailedAuthenticationKey> {
    /**
     * Database Column Remarks:
     *   ダミー項目
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.failed_authentication.dummy
     *
     * @mbg.generated
     */
    private String dummy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms.failed_authentication
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public FailedAuthenticationKey getId() {
        FailedAuthenticationKey superClass = new FailedAuthenticationKey();
        superClass.setUsername(getUsername());
        superClass.setAuthenticationTimestamp(getAuthenticationTimestamp());
        return superClass;
    }
}