package jp.co.stnet.cms.base.domain.model.mbg;

import jp.co.stnet.cms.base.domain.model.KeyInterface;
import jp.co.stnet.cms.base.domain.model.mbg.FailedEmailChangeRequestKey;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

/**
 * Database Table Remarks:
 *   メールアドレス変更の認証失敗の記録
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_failed_email_change_request
 */
@Data
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
@AllArgsConstructor
@ToString(callSuper = true)
@NoArgsConstructor
public class FailedEmailChangeRequest extends FailedEmailChangeRequestKey implements KeyInterface<FailedEmailChangeRequestKey> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_failed_email_change_request.dummy
     *
     * @mbg.generated
     */
    private String dummy;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_failed_email_change_request
     *
     * @mbg.generated
     */
    public FailedEmailChangeRequestKey getPrimaryKey() {
        FailedEmailChangeRequestKey superClass = new FailedEmailChangeRequestKey();
        superClass.setToken(getToken());
        superClass.setAttemptDate(getAttemptDate());
        return superClass;
    }
}