package jp.co.stnet.cms.base.domain.model.mbg;

import jp.co.stnet.cms.base.domain.model.KeyInterface;
import jp.co.stnet.cms.base.domain.model.mbg.FailedPasswordReissueKey;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

/**
 * Database Table Remarks:
 *   パスワード再発行失敗履歴
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_failed_password_reissue
 */
@Data
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
@AllArgsConstructor
@ToString(callSuper = true)
@NoArgsConstructor
public class FailedPasswordReissue extends FailedPasswordReissueKey implements KeyInterface<FailedPasswordReissueKey> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_failed_password_reissue.dummy
     *
     * @mbg.generated
     */
    private String dummy;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_failed_password_reissue
     *
     * @mbg.generated
     */
    public FailedPasswordReissueKey getPrimaryKey() {
        FailedPasswordReissueKey superClass = new FailedPasswordReissueKey();
        superClass.setToken(getToken());
        superClass.setAttemptDate(getAttemptDate());
        return superClass;
    }
}