package jp.co.stnet.cms.base.domain.model.mbg;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

/**
 * Database Table Remarks:
 *   メールアドレス変更の認証失敗の記録
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_failed_email_change_request
 */
@Data
@SuperBuilder
@EqualsAndHashCode
@AllArgsConstructor
@ToString
@NoArgsConstructor
public class FailedEmailChangeRequestKey implements Serializable {
    /**
     * Database Column Remarks:
     *   トークン
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_failed_email_change_request.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     * Database Column Remarks:
     *   試行日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_failed_email_change_request.attempt_date
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy/MM/dd HH:mm:ss")
    private LocalDateTime attemptDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_failed_email_change_request
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}