package jp.co.stnet.cms.base.domain.model.mbg;

import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

/**
 * Database Table Remarks:
 *   パスワード履歴
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_password_history
 */
@Data
@SuperBuilder
@EqualsAndHashCode
@AllArgsConstructor
@ToString
@NoArgsConstructor
public class PasswordHistoryKey {
    /**
     * Database Column Remarks:
     *   ユーザid
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_password_history.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   利用開始日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_password_history.use_from
     *
     * @mbg.generated
     */
    private LocalDateTime useFrom;
}