package jp.co.stnet.cms.base.domain.model.mbg;

import jp.co.stnet.cms.base.domain.model.KeyInterface;
import jp.co.stnet.cms.base.domain.model.mbg.PermissionRoleKey;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

/**
 * Database Table Remarks:
 *   ロール・パーミッション
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_permission_role
 */
@Data
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
@AllArgsConstructor
@ToString(callSuper = true)
@NoArgsConstructor
public class PermissionRole extends PermissionRoleKey implements KeyInterface<PermissionRoleKey> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_permission_role.dummy
     *
     * @mbg.generated
     */
    private String dummy;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_permission_role
     *
     * @mbg.generated
     */
    public PermissionRoleKey getPrimaryKey() {
        PermissionRoleKey superClass = new PermissionRoleKey();
        superClass.setRole(getRole());
        superClass.setPermission(getPermission());
        return superClass;
    }
}