package jp.co.stnet.cms.base.domain.model.mbg;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import jp.co.stnet.cms.base.domain.model.KeyInterface;
import jp.co.stnet.cms.base.domain.model.mbg.SuccessfulAuthenticationKey;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

/**
 * Database Table Remarks:
 *   認証成功履歴
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_successful_authentication
 */
@Data
@SuperBuilder
@EqualsAndHashCode(callSuper = true)
@AllArgsConstructor
@ToString(callSuper = true)
@NoArgsConstructor
public class SuccessfulAuthentication extends SuccessfulAuthenticationKey implements Serializable, KeyInterface<SuccessfulAuthenticationKey> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_successful_authentication.dummy
     *
     * @mbg.generated
     */
    private String dummy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_successful_authentication
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public SuccessfulAuthenticationKey getId() {
        SuccessfulAuthenticationKey superClass = new SuccessfulAuthenticationKey();
        superClass.setUsername(getUsername());
        superClass.setAuthenticationTimestamp(getAuthenticationTimestamp());
        return superClass;
    }
}