package jp.co.stnet.cms.base.domain.model.mbg;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class VariableExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table variable
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table variable
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table variable
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    public VariableExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table variable
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Long value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Long value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Long value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Long value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Long value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Long> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Long> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Long value1, Long value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Long value1, Long value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("created_by like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("created_by not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("created_date is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("created_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(LocalDateTime value) {
            addCriterion("created_date =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(LocalDateTime value) {
            addCriterion("created_date <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(LocalDateTime value) {
            addCriterion("created_date >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_date >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(LocalDateTime value) {
            addCriterion("created_date <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_date <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<LocalDateTime> values) {
            addCriterion("created_date in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<LocalDateTime> values) {
            addCriterion("created_date not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_date between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_date not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByIsNull() {
            addCriterion("last_modified_by is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByIsNotNull() {
            addCriterion("last_modified_by is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByEqualTo(String value) {
            addCriterion("last_modified_by =", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotEqualTo(String value) {
            addCriterion("last_modified_by <>", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByGreaterThan(String value) {
            addCriterion("last_modified_by >", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByGreaterThanOrEqualTo(String value) {
            addCriterion("last_modified_by >=", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByLessThan(String value) {
            addCriterion("last_modified_by <", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByLessThanOrEqualTo(String value) {
            addCriterion("last_modified_by <=", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByLike(String value) {
            addCriterion("last_modified_by like", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotLike(String value) {
            addCriterion("last_modified_by not like", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByIn(List<String> values) {
            addCriterion("last_modified_by in", values, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotIn(List<String> values) {
            addCriterion("last_modified_by not in", values, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByBetween(String value1, String value2) {
            addCriterion("last_modified_by between", value1, value2, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotBetween(String value1, String value2) {
            addCriterion("last_modified_by not between", value1, value2, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNull() {
            addCriterion("last_modified_date is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNotNull() {
            addCriterion("last_modified_date is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateEqualTo(LocalDateTime value) {
            addCriterion("last_modified_date =", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotEqualTo(LocalDateTime value) {
            addCriterion("last_modified_date <>", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThan(LocalDateTime value) {
            addCriterion("last_modified_date >", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("last_modified_date >=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThan(LocalDateTime value) {
            addCriterion("last_modified_date <", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("last_modified_date <=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIn(List<LocalDateTime> values) {
            addCriterion("last_modified_date in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotIn(List<LocalDateTime> values) {
            addCriterion("last_modified_date not in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("last_modified_date between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("last_modified_date not between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andValue1IsNull() {
            addCriterion("value1 is null");
            return (Criteria) this;
        }

        public Criteria andValue1IsNotNull() {
            addCriterion("value1 is not null");
            return (Criteria) this;
        }

        public Criteria andValue1EqualTo(String value) {
            addCriterion("value1 =", value, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1NotEqualTo(String value) {
            addCriterion("value1 <>", value, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1GreaterThan(String value) {
            addCriterion("value1 >", value, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1GreaterThanOrEqualTo(String value) {
            addCriterion("value1 >=", value, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1LessThan(String value) {
            addCriterion("value1 <", value, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1LessThanOrEqualTo(String value) {
            addCriterion("value1 <=", value, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1Like(String value) {
            addCriterion("value1 like", value, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1NotLike(String value) {
            addCriterion("value1 not like", value, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1In(List<String> values) {
            addCriterion("value1 in", values, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1NotIn(List<String> values) {
            addCriterion("value1 not in", values, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1Between(String value1, String value2) {
            addCriterion("value1 between", value1, value2, "value1");
            return (Criteria) this;
        }

        public Criteria andValue1NotBetween(String value1, String value2) {
            addCriterion("value1 not between", value1, value2, "value1");
            return (Criteria) this;
        }

        public Criteria andValue2IsNull() {
            addCriterion("value2 is null");
            return (Criteria) this;
        }

        public Criteria andValue2IsNotNull() {
            addCriterion("value2 is not null");
            return (Criteria) this;
        }

        public Criteria andValue2EqualTo(String value) {
            addCriterion("value2 =", value, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2NotEqualTo(String value) {
            addCriterion("value2 <>", value, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2GreaterThan(String value) {
            addCriterion("value2 >", value, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2GreaterThanOrEqualTo(String value) {
            addCriterion("value2 >=", value, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2LessThan(String value) {
            addCriterion("value2 <", value, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2LessThanOrEqualTo(String value) {
            addCriterion("value2 <=", value, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2Like(String value) {
            addCriterion("value2 like", value, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2NotLike(String value) {
            addCriterion("value2 not like", value, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2In(List<String> values) {
            addCriterion("value2 in", values, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2NotIn(List<String> values) {
            addCriterion("value2 not in", values, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2Between(String value1, String value2) {
            addCriterion("value2 between", value1, value2, "value2");
            return (Criteria) this;
        }

        public Criteria andValue2NotBetween(String value1, String value2) {
            addCriterion("value2 not between", value1, value2, "value2");
            return (Criteria) this;
        }

        public Criteria andValue3IsNull() {
            addCriterion("value3 is null");
            return (Criteria) this;
        }

        public Criteria andValue3IsNotNull() {
            addCriterion("value3 is not null");
            return (Criteria) this;
        }

        public Criteria andValue3EqualTo(String value) {
            addCriterion("value3 =", value, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3NotEqualTo(String value) {
            addCriterion("value3 <>", value, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3GreaterThan(String value) {
            addCriterion("value3 >", value, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3GreaterThanOrEqualTo(String value) {
            addCriterion("value3 >=", value, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3LessThan(String value) {
            addCriterion("value3 <", value, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3LessThanOrEqualTo(String value) {
            addCriterion("value3 <=", value, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3Like(String value) {
            addCriterion("value3 like", value, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3NotLike(String value) {
            addCriterion("value3 not like", value, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3In(List<String> values) {
            addCriterion("value3 in", values, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3NotIn(List<String> values) {
            addCriterion("value3 not in", values, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3Between(String value1, String value2) {
            addCriterion("value3 between", value1, value2, "value3");
            return (Criteria) this;
        }

        public Criteria andValue3NotBetween(String value1, String value2) {
            addCriterion("value3 not between", value1, value2, "value3");
            return (Criteria) this;
        }

        public Criteria andValue4IsNull() {
            addCriterion("value4 is null");
            return (Criteria) this;
        }

        public Criteria andValue4IsNotNull() {
            addCriterion("value4 is not null");
            return (Criteria) this;
        }

        public Criteria andValue4EqualTo(String value) {
            addCriterion("value4 =", value, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4NotEqualTo(String value) {
            addCriterion("value4 <>", value, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4GreaterThan(String value) {
            addCriterion("value4 >", value, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4GreaterThanOrEqualTo(String value) {
            addCriterion("value4 >=", value, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4LessThan(String value) {
            addCriterion("value4 <", value, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4LessThanOrEqualTo(String value) {
            addCriterion("value4 <=", value, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4Like(String value) {
            addCriterion("value4 like", value, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4NotLike(String value) {
            addCriterion("value4 not like", value, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4In(List<String> values) {
            addCriterion("value4 in", values, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4NotIn(List<String> values) {
            addCriterion("value4 not in", values, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4Between(String value1, String value2) {
            addCriterion("value4 between", value1, value2, "value4");
            return (Criteria) this;
        }

        public Criteria andValue4NotBetween(String value1, String value2) {
            addCriterion("value4 not between", value1, value2, "value4");
            return (Criteria) this;
        }

        public Criteria andValue5IsNull() {
            addCriterion("value5 is null");
            return (Criteria) this;
        }

        public Criteria andValue5IsNotNull() {
            addCriterion("value5 is not null");
            return (Criteria) this;
        }

        public Criteria andValue5EqualTo(String value) {
            addCriterion("value5 =", value, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5NotEqualTo(String value) {
            addCriterion("value5 <>", value, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5GreaterThan(String value) {
            addCriterion("value5 >", value, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5GreaterThanOrEqualTo(String value) {
            addCriterion("value5 >=", value, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5LessThan(String value) {
            addCriterion("value5 <", value, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5LessThanOrEqualTo(String value) {
            addCriterion("value5 <=", value, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5Like(String value) {
            addCriterion("value5 like", value, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5NotLike(String value) {
            addCriterion("value5 not like", value, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5In(List<String> values) {
            addCriterion("value5 in", values, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5NotIn(List<String> values) {
            addCriterion("value5 not in", values, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5Between(String value1, String value2) {
            addCriterion("value5 between", value1, value2, "value5");
            return (Criteria) this;
        }

        public Criteria andValue5NotBetween(String value1, String value2) {
            addCriterion("value5 not between", value1, value2, "value5");
            return (Criteria) this;
        }

        public Criteria andValue6IsNull() {
            addCriterion("value6 is null");
            return (Criteria) this;
        }

        public Criteria andValue6IsNotNull() {
            addCriterion("value6 is not null");
            return (Criteria) this;
        }

        public Criteria andValue6EqualTo(String value) {
            addCriterion("value6 =", value, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6NotEqualTo(String value) {
            addCriterion("value6 <>", value, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6GreaterThan(String value) {
            addCriterion("value6 >", value, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6GreaterThanOrEqualTo(String value) {
            addCriterion("value6 >=", value, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6LessThan(String value) {
            addCriterion("value6 <", value, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6LessThanOrEqualTo(String value) {
            addCriterion("value6 <=", value, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6Like(String value) {
            addCriterion("value6 like", value, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6NotLike(String value) {
            addCriterion("value6 not like", value, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6In(List<String> values) {
            addCriterion("value6 in", values, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6NotIn(List<String> values) {
            addCriterion("value6 not in", values, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6Between(String value1, String value2) {
            addCriterion("value6 between", value1, value2, "value6");
            return (Criteria) this;
        }

        public Criteria andValue6NotBetween(String value1, String value2) {
            addCriterion("value6 not between", value1, value2, "value6");
            return (Criteria) this;
        }

        public Criteria andValue7IsNull() {
            addCriterion("value7 is null");
            return (Criteria) this;
        }

        public Criteria andValue7IsNotNull() {
            addCriterion("value7 is not null");
            return (Criteria) this;
        }

        public Criteria andValue7EqualTo(String value) {
            addCriterion("value7 =", value, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7NotEqualTo(String value) {
            addCriterion("value7 <>", value, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7GreaterThan(String value) {
            addCriterion("value7 >", value, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7GreaterThanOrEqualTo(String value) {
            addCriterion("value7 >=", value, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7LessThan(String value) {
            addCriterion("value7 <", value, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7LessThanOrEqualTo(String value) {
            addCriterion("value7 <=", value, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7Like(String value) {
            addCriterion("value7 like", value, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7NotLike(String value) {
            addCriterion("value7 not like", value, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7In(List<String> values) {
            addCriterion("value7 in", values, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7NotIn(List<String> values) {
            addCriterion("value7 not in", values, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7Between(String value1, String value2) {
            addCriterion("value7 between", value1, value2, "value7");
            return (Criteria) this;
        }

        public Criteria andValue7NotBetween(String value1, String value2) {
            addCriterion("value7 not between", value1, value2, "value7");
            return (Criteria) this;
        }

        public Criteria andValue8IsNull() {
            addCriterion("value8 is null");
            return (Criteria) this;
        }

        public Criteria andValue8IsNotNull() {
            addCriterion("value8 is not null");
            return (Criteria) this;
        }

        public Criteria andValue8EqualTo(String value) {
            addCriterion("value8 =", value, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8NotEqualTo(String value) {
            addCriterion("value8 <>", value, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8GreaterThan(String value) {
            addCriterion("value8 >", value, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8GreaterThanOrEqualTo(String value) {
            addCriterion("value8 >=", value, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8LessThan(String value) {
            addCriterion("value8 <", value, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8LessThanOrEqualTo(String value) {
            addCriterion("value8 <=", value, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8Like(String value) {
            addCriterion("value8 like", value, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8NotLike(String value) {
            addCriterion("value8 not like", value, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8In(List<String> values) {
            addCriterion("value8 in", values, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8NotIn(List<String> values) {
            addCriterion("value8 not in", values, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8Between(String value1, String value2) {
            addCriterion("value8 between", value1, value2, "value8");
            return (Criteria) this;
        }

        public Criteria andValue8NotBetween(String value1, String value2) {
            addCriterion("value8 not between", value1, value2, "value8");
            return (Criteria) this;
        }

        public Criteria andValue9IsNull() {
            addCriterion("value9 is null");
            return (Criteria) this;
        }

        public Criteria andValue9IsNotNull() {
            addCriterion("value9 is not null");
            return (Criteria) this;
        }

        public Criteria andValue9EqualTo(String value) {
            addCriterion("value9 =", value, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9NotEqualTo(String value) {
            addCriterion("value9 <>", value, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9GreaterThan(String value) {
            addCriterion("value9 >", value, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9GreaterThanOrEqualTo(String value) {
            addCriterion("value9 >=", value, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9LessThan(String value) {
            addCriterion("value9 <", value, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9LessThanOrEqualTo(String value) {
            addCriterion("value9 <=", value, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9Like(String value) {
            addCriterion("value9 like", value, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9NotLike(String value) {
            addCriterion("value9 not like", value, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9In(List<String> values) {
            addCriterion("value9 in", values, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9NotIn(List<String> values) {
            addCriterion("value9 not in", values, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9Between(String value1, String value2) {
            addCriterion("value9 between", value1, value2, "value9");
            return (Criteria) this;
        }

        public Criteria andValue9NotBetween(String value1, String value2) {
            addCriterion("value9 not between", value1, value2, "value9");
            return (Criteria) this;
        }

        public Criteria andValue10IsNull() {
            addCriterion("value10 is null");
            return (Criteria) this;
        }

        public Criteria andValue10IsNotNull() {
            addCriterion("value10 is not null");
            return (Criteria) this;
        }

        public Criteria andValue10EqualTo(String value) {
            addCriterion("value10 =", value, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10NotEqualTo(String value) {
            addCriterion("value10 <>", value, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10GreaterThan(String value) {
            addCriterion("value10 >", value, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10GreaterThanOrEqualTo(String value) {
            addCriterion("value10 >=", value, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10LessThan(String value) {
            addCriterion("value10 <", value, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10LessThanOrEqualTo(String value) {
            addCriterion("value10 <=", value, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10Like(String value) {
            addCriterion("value10 like", value, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10NotLike(String value) {
            addCriterion("value10 not like", value, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10In(List<String> values) {
            addCriterion("value10 in", values, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10NotIn(List<String> values) {
            addCriterion("value10 not in", values, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10Between(String value1, String value2) {
            addCriterion("value10 between", value1, value2, "value10");
            return (Criteria) this;
        }

        public Criteria andValue10NotBetween(String value1, String value2) {
            addCriterion("value10 not between", value1, value2, "value10");
            return (Criteria) this;
        }

        public Criteria andDate1IsNull() {
            addCriterion("date1 is null");
            return (Criteria) this;
        }

        public Criteria andDate1IsNotNull() {
            addCriterion("date1 is not null");
            return (Criteria) this;
        }

        public Criteria andDate1EqualTo(LocalDate value) {
            addCriterion("date1 =", value, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1NotEqualTo(LocalDate value) {
            addCriterion("date1 <>", value, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1GreaterThan(LocalDate value) {
            addCriterion("date1 >", value, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1GreaterThanOrEqualTo(LocalDate value) {
            addCriterion("date1 >=", value, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1LessThan(LocalDate value) {
            addCriterion("date1 <", value, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1LessThanOrEqualTo(LocalDate value) {
            addCriterion("date1 <=", value, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1In(List<LocalDate> values) {
            addCriterion("date1 in", values, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1NotIn(List<LocalDate> values) {
            addCriterion("date1 not in", values, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1Between(LocalDate value1, LocalDate value2) {
            addCriterion("date1 between", value1, value2, "date1");
            return (Criteria) this;
        }

        public Criteria andDate1NotBetween(LocalDate value1, LocalDate value2) {
            addCriterion("date1 not between", value1, value2, "date1");
            return (Criteria) this;
        }

        public Criteria andDate2IsNull() {
            addCriterion("date2 is null");
            return (Criteria) this;
        }

        public Criteria andDate2IsNotNull() {
            addCriterion("date2 is not null");
            return (Criteria) this;
        }

        public Criteria andDate2EqualTo(LocalDate value) {
            addCriterion("date2 =", value, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2NotEqualTo(LocalDate value) {
            addCriterion("date2 <>", value, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2GreaterThan(LocalDate value) {
            addCriterion("date2 >", value, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2GreaterThanOrEqualTo(LocalDate value) {
            addCriterion("date2 >=", value, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2LessThan(LocalDate value) {
            addCriterion("date2 <", value, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2LessThanOrEqualTo(LocalDate value) {
            addCriterion("date2 <=", value, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2In(List<LocalDate> values) {
            addCriterion("date2 in", values, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2NotIn(List<LocalDate> values) {
            addCriterion("date2 not in", values, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2Between(LocalDate value1, LocalDate value2) {
            addCriterion("date2 between", value1, value2, "date2");
            return (Criteria) this;
        }

        public Criteria andDate2NotBetween(LocalDate value1, LocalDate value2) {
            addCriterion("date2 not between", value1, value2, "date2");
            return (Criteria) this;
        }

        public Criteria andDate3IsNull() {
            addCriterion("date3 is null");
            return (Criteria) this;
        }

        public Criteria andDate3IsNotNull() {
            addCriterion("date3 is not null");
            return (Criteria) this;
        }

        public Criteria andDate3EqualTo(LocalDate value) {
            addCriterion("date3 =", value, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3NotEqualTo(LocalDate value) {
            addCriterion("date3 <>", value, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3GreaterThan(LocalDate value) {
            addCriterion("date3 >", value, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3GreaterThanOrEqualTo(LocalDate value) {
            addCriterion("date3 >=", value, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3LessThan(LocalDate value) {
            addCriterion("date3 <", value, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3LessThanOrEqualTo(LocalDate value) {
            addCriterion("date3 <=", value, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3In(List<LocalDate> values) {
            addCriterion("date3 in", values, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3NotIn(List<LocalDate> values) {
            addCriterion("date3 not in", values, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3Between(LocalDate value1, LocalDate value2) {
            addCriterion("date3 between", value1, value2, "date3");
            return (Criteria) this;
        }

        public Criteria andDate3NotBetween(LocalDate value1, LocalDate value2) {
            addCriterion("date3 not between", value1, value2, "date3");
            return (Criteria) this;
        }

        public Criteria andDate4IsNull() {
            addCriterion("date4 is null");
            return (Criteria) this;
        }

        public Criteria andDate4IsNotNull() {
            addCriterion("date4 is not null");
            return (Criteria) this;
        }

        public Criteria andDate4EqualTo(LocalDate value) {
            addCriterion("date4 =", value, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4NotEqualTo(LocalDate value) {
            addCriterion("date4 <>", value, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4GreaterThan(LocalDate value) {
            addCriterion("date4 >", value, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4GreaterThanOrEqualTo(LocalDate value) {
            addCriterion("date4 >=", value, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4LessThan(LocalDate value) {
            addCriterion("date4 <", value, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4LessThanOrEqualTo(LocalDate value) {
            addCriterion("date4 <=", value, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4In(List<LocalDate> values) {
            addCriterion("date4 in", values, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4NotIn(List<LocalDate> values) {
            addCriterion("date4 not in", values, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4Between(LocalDate value1, LocalDate value2) {
            addCriterion("date4 between", value1, value2, "date4");
            return (Criteria) this;
        }

        public Criteria andDate4NotBetween(LocalDate value1, LocalDate value2) {
            addCriterion("date4 not between", value1, value2, "date4");
            return (Criteria) this;
        }

        public Criteria andDate5IsNull() {
            addCriterion("date5 is null");
            return (Criteria) this;
        }

        public Criteria andDate5IsNotNull() {
            addCriterion("date5 is not null");
            return (Criteria) this;
        }

        public Criteria andDate5EqualTo(LocalDate value) {
            addCriterion("date5 =", value, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5NotEqualTo(LocalDate value) {
            addCriterion("date5 <>", value, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5GreaterThan(LocalDate value) {
            addCriterion("date5 >", value, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5GreaterThanOrEqualTo(LocalDate value) {
            addCriterion("date5 >=", value, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5LessThan(LocalDate value) {
            addCriterion("date5 <", value, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5LessThanOrEqualTo(LocalDate value) {
            addCriterion("date5 <=", value, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5In(List<LocalDate> values) {
            addCriterion("date5 in", values, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5NotIn(List<LocalDate> values) {
            addCriterion("date5 not in", values, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5Between(LocalDate value1, LocalDate value2) {
            addCriterion("date5 between", value1, value2, "date5");
            return (Criteria) this;
        }

        public Criteria andDate5NotBetween(LocalDate value1, LocalDate value2) {
            addCriterion("date5 not between", value1, value2, "date5");
            return (Criteria) this;
        }

        public Criteria andValint1IsNull() {
            addCriterion("valint1 is null");
            return (Criteria) this;
        }

        public Criteria andValint1IsNotNull() {
            addCriterion("valint1 is not null");
            return (Criteria) this;
        }

        public Criteria andValint1EqualTo(Integer value) {
            addCriterion("valint1 =", value, "valint1");
            return (Criteria) this;
        }

        public Criteria andValint1NotEqualTo(Integer value) {
            addCriterion("valint1 <>", value, "valint1");
            return (Criteria) this;
        }

        public Criteria andValint1GreaterThan(Integer value) {
            addCriterion("valint1 >", value, "valint1");
            return (Criteria) this;
        }

        public Criteria andValint1GreaterThanOrEqualTo(Integer value) {
            addCriterion("valint1 >=", value, "valint1");
            return (Criteria) this;
        }

        public Criteria andValint1LessThan(Integer value) {
            addCriterion("valint1 <", value, "valint1");
            return (Criteria) this;
        }

        public Criteria andValint1LessThanOrEqualTo(Integer value) {
            addCriterion("valint1 <=", value, "valint1");
            return (Criteria) this;
        }

        public Criteria andValint1In(List<Integer> values) {
            addCriterion("valint1 in", values, "valint1");
            return (Criteria) this;
        }

        public Criteria andValint1NotIn(List<Integer> values) {
            addCriterion("valint1 not in", values, "valint1");
            return (Criteria) this;
        }

        public Criteria andValint1Between(Integer value1, Integer value2) {
            addCriterion("valint1 between", value1, value2, "valint1");
            return (Criteria) this;
        }

        public Criteria andValint1NotBetween(Integer value1, Integer value2) {
            addCriterion("valint1 not between", value1, value2, "valint1");
            return (Criteria) this;
        }

        public Criteria andValint2IsNull() {
            addCriterion("valint2 is null");
            return (Criteria) this;
        }

        public Criteria andValint2IsNotNull() {
            addCriterion("valint2 is not null");
            return (Criteria) this;
        }

        public Criteria andValint2EqualTo(Integer value) {
            addCriterion("valint2 =", value, "valint2");
            return (Criteria) this;
        }

        public Criteria andValint2NotEqualTo(Integer value) {
            addCriterion("valint2 <>", value, "valint2");
            return (Criteria) this;
        }

        public Criteria andValint2GreaterThan(Integer value) {
            addCriterion("valint2 >", value, "valint2");
            return (Criteria) this;
        }

        public Criteria andValint2GreaterThanOrEqualTo(Integer value) {
            addCriterion("valint2 >=", value, "valint2");
            return (Criteria) this;
        }

        public Criteria andValint2LessThan(Integer value) {
            addCriterion("valint2 <", value, "valint2");
            return (Criteria) this;
        }

        public Criteria andValint2LessThanOrEqualTo(Integer value) {
            addCriterion("valint2 <=", value, "valint2");
            return (Criteria) this;
        }

        public Criteria andValint2In(List<Integer> values) {
            addCriterion("valint2 in", values, "valint2");
            return (Criteria) this;
        }

        public Criteria andValint2NotIn(List<Integer> values) {
            addCriterion("valint2 not in", values, "valint2");
            return (Criteria) this;
        }

        public Criteria andValint2Between(Integer value1, Integer value2) {
            addCriterion("valint2 between", value1, value2, "valint2");
            return (Criteria) this;
        }

        public Criteria andValint2NotBetween(Integer value1, Integer value2) {
            addCriterion("valint2 not between", value1, value2, "valint2");
            return (Criteria) this;
        }

        public Criteria andValint3IsNull() {
            addCriterion("valint3 is null");
            return (Criteria) this;
        }

        public Criteria andValint3IsNotNull() {
            addCriterion("valint3 is not null");
            return (Criteria) this;
        }

        public Criteria andValint3EqualTo(Integer value) {
            addCriterion("valint3 =", value, "valint3");
            return (Criteria) this;
        }

        public Criteria andValint3NotEqualTo(Integer value) {
            addCriterion("valint3 <>", value, "valint3");
            return (Criteria) this;
        }

        public Criteria andValint3GreaterThan(Integer value) {
            addCriterion("valint3 >", value, "valint3");
            return (Criteria) this;
        }

        public Criteria andValint3GreaterThanOrEqualTo(Integer value) {
            addCriterion("valint3 >=", value, "valint3");
            return (Criteria) this;
        }

        public Criteria andValint3LessThan(Integer value) {
            addCriterion("valint3 <", value, "valint3");
            return (Criteria) this;
        }

        public Criteria andValint3LessThanOrEqualTo(Integer value) {
            addCriterion("valint3 <=", value, "valint3");
            return (Criteria) this;
        }

        public Criteria andValint3In(List<Integer> values) {
            addCriterion("valint3 in", values, "valint3");
            return (Criteria) this;
        }

        public Criteria andValint3NotIn(List<Integer> values) {
            addCriterion("valint3 not in", values, "valint3");
            return (Criteria) this;
        }

        public Criteria andValint3Between(Integer value1, Integer value2) {
            addCriterion("valint3 between", value1, value2, "valint3");
            return (Criteria) this;
        }

        public Criteria andValint3NotBetween(Integer value1, Integer value2) {
            addCriterion("valint3 not between", value1, value2, "valint3");
            return (Criteria) this;
        }

        public Criteria andValint4IsNull() {
            addCriterion("valint4 is null");
            return (Criteria) this;
        }

        public Criteria andValint4IsNotNull() {
            addCriterion("valint4 is not null");
            return (Criteria) this;
        }

        public Criteria andValint4EqualTo(Integer value) {
            addCriterion("valint4 =", value, "valint4");
            return (Criteria) this;
        }

        public Criteria andValint4NotEqualTo(Integer value) {
            addCriterion("valint4 <>", value, "valint4");
            return (Criteria) this;
        }

        public Criteria andValint4GreaterThan(Integer value) {
            addCriterion("valint4 >", value, "valint4");
            return (Criteria) this;
        }

        public Criteria andValint4GreaterThanOrEqualTo(Integer value) {
            addCriterion("valint4 >=", value, "valint4");
            return (Criteria) this;
        }

        public Criteria andValint4LessThan(Integer value) {
            addCriterion("valint4 <", value, "valint4");
            return (Criteria) this;
        }

        public Criteria andValint4LessThanOrEqualTo(Integer value) {
            addCriterion("valint4 <=", value, "valint4");
            return (Criteria) this;
        }

        public Criteria andValint4In(List<Integer> values) {
            addCriterion("valint4 in", values, "valint4");
            return (Criteria) this;
        }

        public Criteria andValint4NotIn(List<Integer> values) {
            addCriterion("valint4 not in", values, "valint4");
            return (Criteria) this;
        }

        public Criteria andValint4Between(Integer value1, Integer value2) {
            addCriterion("valint4 between", value1, value2, "valint4");
            return (Criteria) this;
        }

        public Criteria andValint4NotBetween(Integer value1, Integer value2) {
            addCriterion("valint4 not between", value1, value2, "valint4");
            return (Criteria) this;
        }

        public Criteria andValint5IsNull() {
            addCriterion("valint5 is null");
            return (Criteria) this;
        }

        public Criteria andValint5IsNotNull() {
            addCriterion("valint5 is not null");
            return (Criteria) this;
        }

        public Criteria andValint5EqualTo(Integer value) {
            addCriterion("valint5 =", value, "valint5");
            return (Criteria) this;
        }

        public Criteria andValint5NotEqualTo(Integer value) {
            addCriterion("valint5 <>", value, "valint5");
            return (Criteria) this;
        }

        public Criteria andValint5GreaterThan(Integer value) {
            addCriterion("valint5 >", value, "valint5");
            return (Criteria) this;
        }

        public Criteria andValint5GreaterThanOrEqualTo(Integer value) {
            addCriterion("valint5 >=", value, "valint5");
            return (Criteria) this;
        }

        public Criteria andValint5LessThan(Integer value) {
            addCriterion("valint5 <", value, "valint5");
            return (Criteria) this;
        }

        public Criteria andValint5LessThanOrEqualTo(Integer value) {
            addCriterion("valint5 <=", value, "valint5");
            return (Criteria) this;
        }

        public Criteria andValint5In(List<Integer> values) {
            addCriterion("valint5 in", values, "valint5");
            return (Criteria) this;
        }

        public Criteria andValint5NotIn(List<Integer> values) {
            addCriterion("valint5 not in", values, "valint5");
            return (Criteria) this;
        }

        public Criteria andValint5Between(Integer value1, Integer value2) {
            addCriterion("valint5 between", value1, value2, "valint5");
            return (Criteria) this;
        }

        public Criteria andValint5NotBetween(Integer value1, Integer value2) {
            addCriterion("valint5 not between", value1, value2, "valint5");
            return (Criteria) this;
        }

        public Criteria andFile1uuidIsNull() {
            addCriterion("file1uuid is null");
            return (Criteria) this;
        }

        public Criteria andFile1uuidIsNotNull() {
            addCriterion("file1uuid is not null");
            return (Criteria) this;
        }

        public Criteria andFile1uuidEqualTo(String value) {
            addCriterion("file1uuid =", value, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidNotEqualTo(String value) {
            addCriterion("file1uuid <>", value, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidGreaterThan(String value) {
            addCriterion("file1uuid >", value, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidGreaterThanOrEqualTo(String value) {
            addCriterion("file1uuid >=", value, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidLessThan(String value) {
            addCriterion("file1uuid <", value, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidLessThanOrEqualTo(String value) {
            addCriterion("file1uuid <=", value, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidLike(String value) {
            addCriterion("file1uuid like", value, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidNotLike(String value) {
            addCriterion("file1uuid not like", value, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidIn(List<String> values) {
            addCriterion("file1uuid in", values, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidNotIn(List<String> values) {
            addCriterion("file1uuid not in", values, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidBetween(String value1, String value2) {
            addCriterion("file1uuid between", value1, value2, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andFile1uuidNotBetween(String value1, String value2) {
            addCriterion("file1uuid not between", value1, value2, "file1uuid");
            return (Criteria) this;
        }

        public Criteria andTextareaIsNull() {
            addCriterion("textarea is null");
            return (Criteria) this;
        }

        public Criteria andTextareaIsNotNull() {
            addCriterion("textarea is not null");
            return (Criteria) this;
        }

        public Criteria andTextareaEqualTo(String value) {
            addCriterion("textarea =", value, "textarea");
            return (Criteria) this;
        }

        public Criteria andTextareaNotEqualTo(String value) {
            addCriterion("textarea <>", value, "textarea");
            return (Criteria) this;
        }

        public Criteria andTextareaGreaterThan(String value) {
            addCriterion("textarea >", value, "textarea");
            return (Criteria) this;
        }

        public Criteria andTextareaGreaterThanOrEqualTo(String value) {
            addCriterion("textarea >=", value, "textarea");
            return (Criteria) this;
        }

        public Criteria andTextareaLessThan(String value) {
            addCriterion("textarea <", value, "textarea");
            return (Criteria) this;
        }

        public Criteria andTextareaLessThanOrEqualTo(String value) {
            addCriterion("textarea <=", value, "textarea");
            return (Criteria) this;
        }

        public Criteria andTextareaLike(String value) {
            addCriterion("textarea like", value, "textarea");
            return (Criteria) this;
        }

        public Criteria andTextareaNotLike(String value) {
            addCriterion("textarea not like", value, "textarea");
            return (Criteria) this;
        }

        public Criteria andTextareaIn(List<String> values) {
            addCriterion("textarea in", values, "textarea");
            return (Criteria) this;
        }

        public Criteria andTextareaNotIn(List<String> values) {
            addCriterion("textarea not in", values, "textarea");
            return (Criteria) this;
        }

        public Criteria andTextareaBetween(String value1, String value2) {
            addCriterion("textarea between", value1, value2, "textarea");
            return (Criteria) this;
        }

        public Criteria andTextareaNotBetween(String value1, String value2) {
            addCriterion("textarea not between", value1, value2, "textarea");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreatedByLikeInsensitive(String value) {
            addCriterion("upper(created_by) like", value.toUpperCase(), "createdBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByLikeInsensitive(String value) {
            addCriterion("upper(last_modified_by) like", value.toUpperCase(), "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andStatusLikeInsensitive(String value) {
            addCriterion("upper(status) like", value.toUpperCase(), "status");
            return (Criteria) this;
        }

        public Criteria andTypeLikeInsensitive(String value) {
            addCriterion("upper(type) like", value.toUpperCase(), "type");
            return (Criteria) this;
        }

        public Criteria andCodeLikeInsensitive(String value) {
            addCriterion("upper(code) like", value.toUpperCase(), "code");
            return (Criteria) this;
        }

        public Criteria andValue1LikeInsensitive(String value) {
            addCriterion("upper(value1) like", value.toUpperCase(), "value1");
            return (Criteria) this;
        }

        public Criteria andValue2LikeInsensitive(String value) {
            addCriterion("upper(value2) like", value.toUpperCase(), "value2");
            return (Criteria) this;
        }

        public Criteria andValue3LikeInsensitive(String value) {
            addCriterion("upper(value3) like", value.toUpperCase(), "value3");
            return (Criteria) this;
        }

        public Criteria andValue4LikeInsensitive(String value) {
            addCriterion("upper(value4) like", value.toUpperCase(), "value4");
            return (Criteria) this;
        }

        public Criteria andValue5LikeInsensitive(String value) {
            addCriterion("upper(value5) like", value.toUpperCase(), "value5");
            return (Criteria) this;
        }

        public Criteria andValue6LikeInsensitive(String value) {
            addCriterion("upper(value6) like", value.toUpperCase(), "value6");
            return (Criteria) this;
        }

        public Criteria andValue7LikeInsensitive(String value) {
            addCriterion("upper(value7) like", value.toUpperCase(), "value7");
            return (Criteria) this;
        }

        public Criteria andValue8LikeInsensitive(String value) {
            addCriterion("upper(value8) like", value.toUpperCase(), "value8");
            return (Criteria) this;
        }

        public Criteria andValue9LikeInsensitive(String value) {
            addCriterion("upper(value9) like", value.toUpperCase(), "value9");
            return (Criteria) this;
        }

        public Criteria andValue10LikeInsensitive(String value) {
            addCriterion("upper(value10) like", value.toUpperCase(), "value10");
            return (Criteria) this;
        }

        public Criteria andFile1uuidLikeInsensitive(String value) {
            addCriterion("upper(file1uuid) like", value.toUpperCase(), "file1uuid");
            return (Criteria) this;
        }

        public Criteria andTextareaLikeInsensitive(String value) {
            addCriterion("upper(textarea) like", value.toUpperCase(), "textarea");
            return (Criteria) this;
        }

        public Criteria andRemarkLikeInsensitive(String value) {
            addCriterion("upper(remark) like", value.toUpperCase(), "remark");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table variable
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table variable
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}