-- cmsboot.simple_entity definition
DROP TABLE IF EXISTS simple_entity cascade;
CREATE TABLE simple_entity (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NOT NULL,
	created_date timestamp NOT NULL,
	last_modified_by varchar(255) NOT NULL,
	last_modified_date timestamp NOT NULL,
	"version" int8 NOT NULL,
	attached_file01uuid varchar(255) NULL,
	checkbox01 varchar(255) NULL,
	combobox01 varchar(255) NULL,
	combobox02 varchar(255) NULL,
	date01 date NULL,
	datetime01 timestamp NULL,
	radio01 varchar(255) NULL,
	radio02 varchar(255) NULL,
	select01 varchar(255) NULL,
	select03 varchar(255) NULL,
	status varchar(255) NOT NULL,
	text01 varchar(255) NULL,
	text02 int4 NULL,
	text03 float4 NULL,
	text04 int2 NULL,
	textarea01 varchar(255) NULL,
	CONSTRAINT simple_entity_pkey PRIMARY KEY (id)
);


-- cmsboot.simple_entity_max_rev definition
DROP TABLE IF EXISTS simple_entity_max_rev cascade;
CREATE TABLE simple_entity_max_rev (
	id int8 NOT NULL,
	rid int8 NOT NULL,
	CONSTRAINT simple_entity_max_rev_pkey PRIMARY KEY (id)
);

-- cmsboot.simple_entity_revision definition
DROP TABLE IF EXISTS simple_entity_revision cascade;
CREATE TABLE simple_entity_revision (
	rid int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	created_by varchar(255) NULL,
	created_date timestamp NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamp NULL,
	rev_type int4 NOT NULL,
	"version" int8 NOT NULL,
	attached_file01uuid varchar(255) NULL,
	checkbox01 varchar(255) NULL,
	combobox01 varchar(255) NULL,
	combobox02 varchar(255) NULL,
	date01 date NULL,
	datetime01 timestamp NULL,
	id int8 NOT NULL,
	radio01 varchar(255) NULL,
	radio02 varchar(255) NULL,
	select01 varchar(255) NULL,
	select03 varchar(255) NULL,
	status varchar(255) NOT NULL,
	text01 varchar(255) NULL,
	text02 int4 NULL,
	text03 float4 NULL,
	text04 bool NULL,
	textarea01 varchar(255) NULL,
	CONSTRAINT simple_entity_revision_pkey PRIMARY KEY (rid)
);


-- cmsboot.simple_entity_checkbox02 definition
DROP TABLE IF EXISTS simple_entity_checkbox02 cascade;
CREATE TABLE simple_entity_checkbox02 (
	simple_entity_id int8 NOT NULL,
	checkbox02 varchar(255) NULL,
	CONSTRAINT fkrmv44v1sgjx7l30nrw3erf0re FOREIGN KEY (simple_entity_id) REFERENCES simple_entity(id)
);


-- cmsboot.simple_entity_combobox03 definition
DROP TABLE IF EXISTS simple_entity_combobox03 cascade ;
CREATE TABLE simple_entity_combobox03 (
	simple_entity_id int8 NOT NULL,
	combobox03 varchar(255) NULL,
	CONSTRAINT fkilbmxju7vidne5iwurrto4fn2 FOREIGN KEY (simple_entity_id) REFERENCES simple_entity(id)
);


-- cmsboot.simple_entity_line_items definition
DROP TABLE IF EXISTS simple_entity_line_items cascade ;
CREATE TABLE simple_entity_line_items (
	simple_entity_id int8 NOT NULL,
	item_name varchar(255) NULL,
	item_no int8 NULL,
	item_number int4 NULL,
	unit_prise int4 NULL,
	CONSTRAINT fk9p2ff74vnn6dpq4gu0edaw9iw FOREIGN KEY (simple_entity_id) REFERENCES simple_entity(id)
);


-- cmsboot.simple_entity_revision_checkbox02 definition
DROP TABLE IF EXISTS simple_entity_revision_checkbox02 cascade ;
CREATE TABLE simple_entity_revision_checkbox02 (
	simple_entity_revision_rid int8 NOT NULL,
	checkbox02 varchar(255) NULL,
	CONSTRAINT fkjj2hm7b5c3xv6foi51n20wy06 FOREIGN KEY (simple_entity_revision_rid) REFERENCES simple_entity_revision(rid)
);


-- cmsboot.simple_entity_revision_combobox03 definition
DROP TABLE IF EXISTS simple_entity_revision_combobox03 cascade ;
CREATE TABLE simple_entity_revision_combobox03 (
	simple_entity_revision_rid int8 NOT NULL,
	combobox03 varchar(255) NULL,
	CONSTRAINT fkos8picdxl023m189uqeyut1yr FOREIGN KEY (simple_entity_revision_rid) REFERENCES simple_entity_revision(rid)
);


-- cmsboot.simple_entity_revision_line_items definition
DROP TABLE IF EXISTS simple_entity_revision_line_items cascade ;
CREATE TABLE simple_entity_revision_line_items (
	simple_entity_revision_rid int8 NOT NULL,
	item_name varchar(255) NULL,
	item_no int8 NULL,
	item_number int4 NULL,
	unit_prise int4 NULL,
	CONSTRAINT fkm74nkmtffqq3pnaffiwumrk5h FOREIGN KEY (simple_entity_revision_rid) REFERENCES simple_entity_revision(rid)
);


-- cmsboot.simple_entity_revision_select02 definition
DROP TABLE IF EXISTS simple_entity_revision_select02 cascade ;
CREATE TABLE simple_entity_revision_select02 (
	simple_entity_revision_rid int8 NOT NULL,
	select02 varchar(255) NULL,
	CONSTRAINT fks6pq89gb97b3v5bdebnkp2dda FOREIGN KEY (simple_entity_revision_rid) REFERENCES simple_entity_revision(rid)
);


-- cmsboot.simple_entity_revision_select04 definition
DROP TABLE IF EXISTS simple_entity_revision_select04 cascade ;
CREATE TABLE simple_entity_revision_select04 (
	simple_entity_revision_rid int8 NOT NULL,
	select04 varchar(255) NULL,
	CONSTRAINT fkoxks4uuxq3yxse7iydlvfvd5w FOREIGN KEY (simple_entity_revision_rid) REFERENCES simple_entity_revision(rid)
);


-- cmsboot.simple_entity_revision_text05 definition
DROP TABLE IF EXISTS simple_entity_revision_text05 cascade ;
CREATE TABLE simple_entity_revision_text05 (
	simple_entity_revision_rid int8 NOT NULL,
	text05 varchar(255) NULL,
	CONSTRAINT fkkmxcf81bd8vgmasf649wlg1ux FOREIGN KEY (simple_entity_revision_rid) REFERENCES simple_entity_revision(rid)
);


-- cmsboot.simple_entity_select02 definition
DROP TABLE IF EXISTS simple_entity_select02 cascade ;
CREATE TABLE simple_entity_select02 (
	simple_entity_id int8 NOT NULL,
	select02 varchar(255) NULL,
	CONSTRAINT fk221mpw54qo7ostpnqtecb4jv5 FOREIGN KEY (simple_entity_id) REFERENCES simple_entity(id)
);


-- cmsboot.simple_entity_select04 definition
DROP TABLE IF EXISTS simple_entity_select04 cascade ;
CREATE TABLE simple_entity_select04 (
	simple_entity_id int8 NOT NULL,
	select04 varchar(255) NULL,
	CONSTRAINT fkg0f3xp1brlfmr8etthrvaq2el FOREIGN KEY (simple_entity_id) REFERENCES simple_entity(id)
);


-- cmsboot.simple_entity_text05 definition
DROP TABLE IF EXISTS simple_entity_text05 cascade ;
CREATE TABLE simple_entity_text05 (
	simple_entity_id int8 NOT NULL,
	text05 varchar(255) NULL,
	CONSTRAINT fkeaiyyh79glf138bqsneolhd9k FOREIGN KEY (simple_entity_id) REFERENCES simple_entity(id)
);

create view v_simple_entity as
select
	se.id,
	se.created_by,
	se.created_date,
	se.last_modified_by,
	se.last_modified_date,
	se.version,
	se.attached_file01uuid,
	se.checkbox01,
	se.combobox01,
	se.combobox02,
	se.date01,
	se.datetime01,
	se.radio01,
	se.radio02,
	se.select01,
	se.select03,
	se.status,
	se.text01,
	se.text02,
	se.text03,
	se.text04,
	se.textarea01,
	cb2.simple_entity_id as cb2_id,
	cb2.checkbox02,
	cb3.simple_entity_id as cb3_id,
	cb3.combobox03,
	st2.simple_entity_id as st2_id,
	st2.select02,
	st4.simple_entity_id as st4_id,
	st4.select04,
	tx5.simple_entity_id as tx5_id,
	tx5.text05
from
	simple_entity se
left outer join simple_entity_checkbox02 cb2 on	cb2.simple_entity_id = se.id
left outer join simple_entity_combobox03 cb3 on	cb3.simple_entity_id = se.id
left outer join simple_entity_select02 st2   on st2.simple_entity_id = se.id
left outer join simple_entity_select04 st4   on	st4.simple_entity_id = se.id
left outer join simple_entity_text05 tx5     on	tx5.simple_entity_id = se.id
;