package jp.co.stnet.cms.equipment.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.base.infrastructure.mapper.VersionMapperInterface;
import jp.co.stnet.cms.equipment.domain.model.mbg.ApprovalFlow;
import jp.co.stnet.cms.equipment.domain.model.mbg.ApprovalFlowExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface ApprovalFlowMapper extends VersionMapperInterface<ApprovalFlow, ApprovalFlowExample, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow
     *
     * @mbg.generated
     */
    long countByExample(ApprovalFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow
     *
     * @mbg.generated
     */
    int deleteByExample(ApprovalFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long approvalFlowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow
     *
     * @mbg.generated
     */
    int insert(ApprovalFlow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow
     *
     * @mbg.generated
     */
    int insertSelective(ApprovalFlow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow
     *
     * @mbg.generated
     */
    List<ApprovalFlow> selectByExampleWithRowbounds(ApprovalFlowExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow
     *
     * @mbg.generated
     */
    List<ApprovalFlow> selectByExample(ApprovalFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow
     *
     * @mbg.generated
     */
    ApprovalFlow selectByPrimaryKey(Long approvalFlowId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") ApprovalFlow row, @Param("example") ApprovalFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") ApprovalFlow row, @Param("example") ApprovalFlowExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersionSelective(ApprovalFlow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApprovalFlow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersion(ApprovalFlow row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApprovalFlow row);
}