package jp.co.stnet.cms.equipment.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.base.infrastructure.mapper.VersionMapperInterface;
import jp.co.stnet.cms.equipment.domain.model.mbg.ConfirmHistory;
import jp.co.stnet.cms.equipment.domain.model.mbg.ConfirmHistoryExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface ConfirmHistoryMapper extends VersionMapperInterface<ConfirmHistory, ConfirmHistoryExample, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_history
     *
     * @mbg.generated
     */
    long countByExample(ConfirmHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_history
     *
     * @mbg.generated
     */
    int deleteByExample(ConfirmHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long confirmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_history
     *
     * @mbg.generated
     */
    int insert(ConfirmHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_history
     *
     * @mbg.generated
     */
    int insertSelective(ConfirmHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_history
     *
     * @mbg.generated
     */
    List<ConfirmHistory> selectByExampleWithRowbounds(ConfirmHistoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_history
     *
     * @mbg.generated
     */
    List<ConfirmHistory> selectByExample(ConfirmHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_history
     *
     * @mbg.generated
     */
    ConfirmHistory selectByPrimaryKey(Long confirmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") ConfirmHistory row, @Param("example") ConfirmHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") ConfirmHistory row, @Param("example") ConfirmHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersionSelective(ConfirmHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConfirmHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersion(ConfirmHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table confirm_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConfirmHistory row);
}