package jp.co.stnet.cms.equipment.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.base.infrastructure.mapper.VersionMapperInterface;
import jp.co.stnet.cms.equipment.domain.model.mbg.EquipType;
import jp.co.stnet.cms.equipment.domain.model.mbg.EquipTypeExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface EquipTypeMapper extends VersionMapperInterface<EquipType, EquipTypeExample, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equip_type
     *
     * @mbg.generated
     */
    long countByExample(EquipTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equip_type
     *
     * @mbg.generated
     */
    int deleteByExample(EquipTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equip_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long equipTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equip_type
     *
     * @mbg.generated
     */
    int insert(EquipType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equip_type
     *
     * @mbg.generated
     */
    int insertSelective(EquipType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equip_type
     *
     * @mbg.generated
     */
    List<EquipType> selectByExampleWithRowbounds(EquipTypeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equip_type
     *
     * @mbg.generated
     */
    List<EquipType> selectByExample(EquipTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equip_type
     *
     * @mbg.generated
     */
    EquipType selectByPrimaryKey(Long equipTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equip_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") EquipType row, @Param("example") EquipTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equip_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") EquipType row, @Param("example") EquipTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equip_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersionSelective(EquipType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equip_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EquipType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equip_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersion(EquipType row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table equip_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EquipType row);
}