package jp.co.stnet.cms.equipment.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.base.infrastructure.mapper.VersionMapperInterface;
import jp.co.stnet.cms.equipment.domain.model.mbg.RequestEquip;
import jp.co.stnet.cms.equipment.domain.model.mbg.RequestEquipExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface RequestEquipMapper extends VersionMapperInterface<RequestEquip, RequestEquipExample, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_equip
     *
     * @mbg.generated
     */
    long countByExample(RequestEquipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_equip
     *
     * @mbg.generated
     */
    int deleteByExample(RequestEquipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_equip
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long requestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_equip
     *
     * @mbg.generated
     */
    int insert(RequestEquip row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_equip
     *
     * @mbg.generated
     */
    int insertSelective(RequestEquip row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_equip
     *
     * @mbg.generated
     */
    List<RequestEquip> selectByExampleWithRowbounds(RequestEquipExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_equip
     *
     * @mbg.generated
     */
    List<RequestEquip> selectByExample(RequestEquipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_equip
     *
     * @mbg.generated
     */
    RequestEquip selectByPrimaryKey(Long requestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_equip
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") RequestEquip row, @Param("example") RequestEquipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_equip
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") RequestEquip row, @Param("example") RequestEquipExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_equip
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersionSelective(RequestEquip row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_equip
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RequestEquip row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_equip
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersion(RequestEquip row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request_equip
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RequestEquip row);
}