package jp.co.stnet.cms.equipment.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.base.infrastructure.mapper.ViewMapperInterface;
import jp.co.stnet.cms.equipment.domain.model.mbg.VEmployee;
import jp.co.stnet.cms.equipment.domain.model.mbg.VEmployeeExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface VEmployeeMapper extends ViewMapperInterface<VEmployee, VEmployeeExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_employee
     *
     * @mbg.generated
     */
    long countByExample(VEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_employee
     *
     * @mbg.generated
     */
    List<VEmployee> selectByExampleWithRowbounds(VEmployeeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_employee
     *
     * @mbg.generated
     */
    List<VEmployee> selectByExample(VEmployeeExample example);
}