package jp.co.stnet.cms.base.infrastructure.mapper;

import java.util.List;
import jp.co.stnet.cms.base.domain.model.Person;
import jp.co.stnet.cms.base.domain.model.PersonExample;
import jp.co.stnet.cms.base.domain.model.PersonKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface PersonMapper extends MapperInterface<Person, PersonExample, PersonKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.person
     *
     * @mbg.generated
     */
    @Override
    long countByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.person
     *
     * @mbg.generated
     */
    @Override
    int deleteByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.person
     *
     * @mbg.generated
     */
    @Override
    int deleteByPrimaryKey(PersonKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.person
     *
     * @mbg.generated
     */
    @Override
    int insert(Person row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.person
     *
     * @mbg.generated
     */
    @Override
    int insertSelective(Person row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.person
     *
     * @mbg.generated
     */
    List<Person> selectByExampleWithRowbounds(PersonExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.person
     *
     * @mbg.generated
     */
    @Override
    List<Person> selectByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.person
     *
     * @mbg.generated
     */
    @Override
    Person selectByPrimaryKey(PersonKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.person
     *
     * @mbg.generated
     */
    @Override
    int updateByExampleSelective(@Param("row") Person row, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.person
     *
     * @mbg.generated
     */
    @Override
    int updateByExample(@Param("row") Person row, @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.person
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersionSelective(Person row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.person
     *
     * @mbg.generated
     */
    @Override
    int updateByPrimaryKeySelective(Person row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.person
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersion(Person row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.person
     *
     * @mbg.generated
     */
    @Override
    int updateByPrimaryKey(Person row);
}