package jp.co.stnet.cms.example.domain.model.mbg;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table simple_entity_line_items
 */
@Data
@SuperBuilder
@EqualsAndHashCode
@AllArgsConstructor
@ToString
@NoArgsConstructor
public class LineItem implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_line_items.simple_entity_id
     *
     * @mbg.generated
     */
    private Long simpleEntityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_line_items.item_name
     *
     * @mbg.generated
     */
    private String itemName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_line_items.item_no
     *
     * @mbg.generated
     */
    private Long itemNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_line_items.item_number
     *
     * @mbg.generated
     */
    private Integer itemNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_line_items.unit_prise
     *
     * @mbg.generated
     */
    private Integer unitPrise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table simple_entity_line_items
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;
}