package jp.co.stnet.cms.example.domain.model.mbg;

import java.time.LocalDate;
import java.time.LocalDateTime;
import jp.co.stnet.cms.base.domain.model.KeyInterface;
import jp.co.stnet.cms.base.domain.model.StatusInterface;
import jp.co.stnet.cms.base.domain.model.VersionInterface;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table simple_entity_revision
 */
@Data
@SuperBuilder
@EqualsAndHashCode
@AllArgsConstructor
@ToString
@NoArgsConstructor
public class SimpleEntityRevision implements KeyInterface<Long>, VersionInterface, StatusInterface {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.rid
     *
     * @mbg.generated
     */
    private Long rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.created_by
     *
     * @mbg.generated
     */
    @EqualsAndHashCode.Exclude
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.created_date
     *
     * @mbg.generated
     */
    @EqualsAndHashCode.Exclude
    private LocalDateTime createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.last_modified_by
     *
     * @mbg.generated
     */
    @EqualsAndHashCode.Exclude
    private String lastModifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.last_modified_date
     *
     * @mbg.generated
     */
    @EqualsAndHashCode.Exclude
    private LocalDateTime lastModifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.rev_type
     *
     * @mbg.generated
     */
    private Integer revType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.version
     *
     * @mbg.generated
     */
    @EqualsAndHashCode.Exclude
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.attached_file01uuid
     *
     * @mbg.generated
     */
    private String attachedFile01uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.checkbox01
     *
     * @mbg.generated
     */
    private String checkbox01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.combobox01
     *
     * @mbg.generated
     */
    private String combobox01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.combobox02
     *
     * @mbg.generated
     */
    private String combobox02;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.date01
     *
     * @mbg.generated
     */
    private LocalDate date01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.datetime01
     *
     * @mbg.generated
     */
    private LocalDateTime datetime01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.radio01
     *
     * @mbg.generated
     */
    private Boolean radio01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.radio02
     *
     * @mbg.generated
     */
    private String radio02;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.select01
     *
     * @mbg.generated
     */
    private String select01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.select03
     *
     * @mbg.generated
     */
    private String select03;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.text01
     *
     * @mbg.generated
     */
    private String text01;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.text02
     *
     * @mbg.generated
     */
    private Integer text02;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.text03
     *
     * @mbg.generated
     */
    private Float text03;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.text04
     *
     * @mbg.generated
     */
    private Boolean text04;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column simple_entity_revision.textarea01
     *
     * @mbg.generated
     */
    private String textarea01;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_revision
     *
     * @mbg.generated
     */
    public Long getPrimaryKey() {
        return getRid();
    }
}