package jp.co.stnet.cms.example.domain.model.mbg;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import lombok.EqualsAndHashCode;

public class TSimpleEntityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    public TSimpleEntityExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(String value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(String value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(String value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(String value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(String value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(String value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLike(String value) {
            addCriterion("created_by like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotLike(String value) {
            addCriterion("created_by not like", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<String> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<String> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(String value1, String value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(String value1, String value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNull() {
            addCriterion("created_date is null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIsNotNull() {
            addCriterion("created_date is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedDateEqualTo(LocalDateTime value) {
            addCriterion("created_date =", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotEqualTo(LocalDateTime value) {
            addCriterion("created_date <>", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThan(LocalDateTime value) {
            addCriterion("created_date >", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_date >=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThan(LocalDateTime value) {
            addCriterion("created_date <", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("created_date <=", value, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateIn(List<LocalDateTime> values) {
            addCriterion("created_date in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotIn(List<LocalDateTime> values) {
            addCriterion("created_date not in", values, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_date between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andCreatedDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("created_date not between", value1, value2, "createdDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByIsNull() {
            addCriterion("last_modified_by is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByIsNotNull() {
            addCriterion("last_modified_by is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByEqualTo(String value) {
            addCriterion("last_modified_by =", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotEqualTo(String value) {
            addCriterion("last_modified_by <>", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByGreaterThan(String value) {
            addCriterion("last_modified_by >", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByGreaterThanOrEqualTo(String value) {
            addCriterion("last_modified_by >=", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByLessThan(String value) {
            addCriterion("last_modified_by <", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByLessThanOrEqualTo(String value) {
            addCriterion("last_modified_by <=", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByLike(String value) {
            addCriterion("last_modified_by like", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotLike(String value) {
            addCriterion("last_modified_by not like", value, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByIn(List<String> values) {
            addCriterion("last_modified_by in", values, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotIn(List<String> values) {
            addCriterion("last_modified_by not in", values, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByBetween(String value1, String value2) {
            addCriterion("last_modified_by between", value1, value2, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByNotBetween(String value1, String value2) {
            addCriterion("last_modified_by not between", value1, value2, "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNull() {
            addCriterion("last_modified_date is null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIsNotNull() {
            addCriterion("last_modified_date is not null");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateEqualTo(LocalDateTime value) {
            addCriterion("last_modified_date =", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotEqualTo(LocalDateTime value) {
            addCriterion("last_modified_date <>", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThan(LocalDateTime value) {
            addCriterion("last_modified_date >", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("last_modified_date >=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThan(LocalDateTime value) {
            addCriterion("last_modified_date <", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("last_modified_date <=", value, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateIn(List<LocalDateTime> values) {
            addCriterion("last_modified_date in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotIn(List<LocalDateTime> values) {
            addCriterion("last_modified_date not in", values, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("last_modified_date between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andLastModifiedDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("last_modified_date not between", value1, value2, "lastModifiedDate");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Long value) {
            addCriterion("version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Long value) {
            addCriterion("version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Long value) {
            addCriterion("version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Long value) {
            addCriterion("version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Long value) {
            addCriterion("version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Long value) {
            addCriterion("version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Long> values) {
            addCriterion("version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Long> values) {
            addCriterion("version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Long value1, Long value2) {
            addCriterion("version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Long value1, Long value2) {
            addCriterion("version not between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andAttachedFile01uuidIsNull() {
            addCriterion("attached_file01uuid is null");
            return (Criteria) this;
        }

        public Criteria andAttachedFile01uuidIsNotNull() {
            addCriterion("attached_file01uuid is not null");
            return (Criteria) this;
        }

        public Criteria andAttachedFile01uuidEqualTo(String value) {
            addCriterion("attached_file01uuid =", value, "attachedFile01uuid");
            return (Criteria) this;
        }

        public Criteria andAttachedFile01uuidNotEqualTo(String value) {
            addCriterion("attached_file01uuid <>", value, "attachedFile01uuid");
            return (Criteria) this;
        }

        public Criteria andAttachedFile01uuidGreaterThan(String value) {
            addCriterion("attached_file01uuid >", value, "attachedFile01uuid");
            return (Criteria) this;
        }

        public Criteria andAttachedFile01uuidGreaterThanOrEqualTo(String value) {
            addCriterion("attached_file01uuid >=", value, "attachedFile01uuid");
            return (Criteria) this;
        }

        public Criteria andAttachedFile01uuidLessThan(String value) {
            addCriterion("attached_file01uuid <", value, "attachedFile01uuid");
            return (Criteria) this;
        }

        public Criteria andAttachedFile01uuidLessThanOrEqualTo(String value) {
            addCriterion("attached_file01uuid <=", value, "attachedFile01uuid");
            return (Criteria) this;
        }

        public Criteria andAttachedFile01uuidLike(String value) {
            addCriterion("attached_file01uuid like", value, "attachedFile01uuid");
            return (Criteria) this;
        }

        public Criteria andAttachedFile01uuidNotLike(String value) {
            addCriterion("attached_file01uuid not like", value, "attachedFile01uuid");
            return (Criteria) this;
        }

        public Criteria andAttachedFile01uuidIn(List<String> values) {
            addCriterion("attached_file01uuid in", values, "attachedFile01uuid");
            return (Criteria) this;
        }

        public Criteria andAttachedFile01uuidNotIn(List<String> values) {
            addCriterion("attached_file01uuid not in", values, "attachedFile01uuid");
            return (Criteria) this;
        }

        public Criteria andAttachedFile01uuidBetween(String value1, String value2) {
            addCriterion("attached_file01uuid between", value1, value2, "attachedFile01uuid");
            return (Criteria) this;
        }

        public Criteria andAttachedFile01uuidNotBetween(String value1, String value2) {
            addCriterion("attached_file01uuid not between", value1, value2, "attachedFile01uuid");
            return (Criteria) this;
        }

        public Criteria andCheckbox01IsNull() {
            addCriterion("checkbox01 is null");
            return (Criteria) this;
        }

        public Criteria andCheckbox01IsNotNull() {
            addCriterion("checkbox01 is not null");
            return (Criteria) this;
        }

        public Criteria andCheckbox01EqualTo(String value) {
            addCriterion("checkbox01 =", value, "checkbox01");
            return (Criteria) this;
        }

        public Criteria andCheckbox01NotEqualTo(String value) {
            addCriterion("checkbox01 <>", value, "checkbox01");
            return (Criteria) this;
        }

        public Criteria andCheckbox01GreaterThan(String value) {
            addCriterion("checkbox01 >", value, "checkbox01");
            return (Criteria) this;
        }

        public Criteria andCheckbox01GreaterThanOrEqualTo(String value) {
            addCriterion("checkbox01 >=", value, "checkbox01");
            return (Criteria) this;
        }

        public Criteria andCheckbox01LessThan(String value) {
            addCriterion("checkbox01 <", value, "checkbox01");
            return (Criteria) this;
        }

        public Criteria andCheckbox01LessThanOrEqualTo(String value) {
            addCriterion("checkbox01 <=", value, "checkbox01");
            return (Criteria) this;
        }

        public Criteria andCheckbox01Like(String value) {
            addCriterion("checkbox01 like", value, "checkbox01");
            return (Criteria) this;
        }

        public Criteria andCheckbox01NotLike(String value) {
            addCriterion("checkbox01 not like", value, "checkbox01");
            return (Criteria) this;
        }

        public Criteria andCheckbox01In(List<String> values) {
            addCriterion("checkbox01 in", values, "checkbox01");
            return (Criteria) this;
        }

        public Criteria andCheckbox01NotIn(List<String> values) {
            addCriterion("checkbox01 not in", values, "checkbox01");
            return (Criteria) this;
        }

        public Criteria andCheckbox01Between(String value1, String value2) {
            addCriterion("checkbox01 between", value1, value2, "checkbox01");
            return (Criteria) this;
        }

        public Criteria andCheckbox01NotBetween(String value1, String value2) {
            addCriterion("checkbox01 not between", value1, value2, "checkbox01");
            return (Criteria) this;
        }

        public Criteria andCombobox01IsNull() {
            addCriterion("combobox01 is null");
            return (Criteria) this;
        }

        public Criteria andCombobox01IsNotNull() {
            addCriterion("combobox01 is not null");
            return (Criteria) this;
        }

        public Criteria andCombobox01EqualTo(String value) {
            addCriterion("combobox01 =", value, "combobox01");
            return (Criteria) this;
        }

        public Criteria andCombobox01NotEqualTo(String value) {
            addCriterion("combobox01 <>", value, "combobox01");
            return (Criteria) this;
        }

        public Criteria andCombobox01GreaterThan(String value) {
            addCriterion("combobox01 >", value, "combobox01");
            return (Criteria) this;
        }

        public Criteria andCombobox01GreaterThanOrEqualTo(String value) {
            addCriterion("combobox01 >=", value, "combobox01");
            return (Criteria) this;
        }

        public Criteria andCombobox01LessThan(String value) {
            addCriterion("combobox01 <", value, "combobox01");
            return (Criteria) this;
        }

        public Criteria andCombobox01LessThanOrEqualTo(String value) {
            addCriterion("combobox01 <=", value, "combobox01");
            return (Criteria) this;
        }

        public Criteria andCombobox01Like(String value) {
            addCriterion("combobox01 like", value, "combobox01");
            return (Criteria) this;
        }

        public Criteria andCombobox01NotLike(String value) {
            addCriterion("combobox01 not like", value, "combobox01");
            return (Criteria) this;
        }

        public Criteria andCombobox01In(List<String> values) {
            addCriterion("combobox01 in", values, "combobox01");
            return (Criteria) this;
        }

        public Criteria andCombobox01NotIn(List<String> values) {
            addCriterion("combobox01 not in", values, "combobox01");
            return (Criteria) this;
        }

        public Criteria andCombobox01Between(String value1, String value2) {
            addCriterion("combobox01 between", value1, value2, "combobox01");
            return (Criteria) this;
        }

        public Criteria andCombobox01NotBetween(String value1, String value2) {
            addCriterion("combobox01 not between", value1, value2, "combobox01");
            return (Criteria) this;
        }

        public Criteria andCombobox02IsNull() {
            addCriterion("combobox02 is null");
            return (Criteria) this;
        }

        public Criteria andCombobox02IsNotNull() {
            addCriterion("combobox02 is not null");
            return (Criteria) this;
        }

        public Criteria andCombobox02EqualTo(String value) {
            addCriterion("combobox02 =", value, "combobox02");
            return (Criteria) this;
        }

        public Criteria andCombobox02NotEqualTo(String value) {
            addCriterion("combobox02 <>", value, "combobox02");
            return (Criteria) this;
        }

        public Criteria andCombobox02GreaterThan(String value) {
            addCriterion("combobox02 >", value, "combobox02");
            return (Criteria) this;
        }

        public Criteria andCombobox02GreaterThanOrEqualTo(String value) {
            addCriterion("combobox02 >=", value, "combobox02");
            return (Criteria) this;
        }

        public Criteria andCombobox02LessThan(String value) {
            addCriterion("combobox02 <", value, "combobox02");
            return (Criteria) this;
        }

        public Criteria andCombobox02LessThanOrEqualTo(String value) {
            addCriterion("combobox02 <=", value, "combobox02");
            return (Criteria) this;
        }

        public Criteria andCombobox02Like(String value) {
            addCriterion("combobox02 like", value, "combobox02");
            return (Criteria) this;
        }

        public Criteria andCombobox02NotLike(String value) {
            addCriterion("combobox02 not like", value, "combobox02");
            return (Criteria) this;
        }

        public Criteria andCombobox02In(List<String> values) {
            addCriterion("combobox02 in", values, "combobox02");
            return (Criteria) this;
        }

        public Criteria andCombobox02NotIn(List<String> values) {
            addCriterion("combobox02 not in", values, "combobox02");
            return (Criteria) this;
        }

        public Criteria andCombobox02Between(String value1, String value2) {
            addCriterion("combobox02 between", value1, value2, "combobox02");
            return (Criteria) this;
        }

        public Criteria andCombobox02NotBetween(String value1, String value2) {
            addCriterion("combobox02 not between", value1, value2, "combobox02");
            return (Criteria) this;
        }

        public Criteria andDate01IsNull() {
            addCriterion("date01 is null");
            return (Criteria) this;
        }

        public Criteria andDate01IsNotNull() {
            addCriterion("date01 is not null");
            return (Criteria) this;
        }

        public Criteria andDate01EqualTo(LocalDate value) {
            addCriterion("date01 =", value, "date01");
            return (Criteria) this;
        }

        public Criteria andDate01NotEqualTo(LocalDate value) {
            addCriterion("date01 <>", value, "date01");
            return (Criteria) this;
        }

        public Criteria andDate01GreaterThan(LocalDate value) {
            addCriterion("date01 >", value, "date01");
            return (Criteria) this;
        }

        public Criteria andDate01GreaterThanOrEqualTo(LocalDate value) {
            addCriterion("date01 >=", value, "date01");
            return (Criteria) this;
        }

        public Criteria andDate01LessThan(LocalDate value) {
            addCriterion("date01 <", value, "date01");
            return (Criteria) this;
        }

        public Criteria andDate01LessThanOrEqualTo(LocalDate value) {
            addCriterion("date01 <=", value, "date01");
            return (Criteria) this;
        }

        public Criteria andDate01In(List<LocalDate> values) {
            addCriterion("date01 in", values, "date01");
            return (Criteria) this;
        }

        public Criteria andDate01NotIn(List<LocalDate> values) {
            addCriterion("date01 not in", values, "date01");
            return (Criteria) this;
        }

        public Criteria andDate01Between(LocalDate value1, LocalDate value2) {
            addCriterion("date01 between", value1, value2, "date01");
            return (Criteria) this;
        }

        public Criteria andDate01NotBetween(LocalDate value1, LocalDate value2) {
            addCriterion("date01 not between", value1, value2, "date01");
            return (Criteria) this;
        }

        public Criteria andDatetime01IsNull() {
            addCriterion("datetime01 is null");
            return (Criteria) this;
        }

        public Criteria andDatetime01IsNotNull() {
            addCriterion("datetime01 is not null");
            return (Criteria) this;
        }

        public Criteria andDatetime01EqualTo(LocalDateTime value) {
            addCriterion("datetime01 =", value, "datetime01");
            return (Criteria) this;
        }

        public Criteria andDatetime01NotEqualTo(LocalDateTime value) {
            addCriterion("datetime01 <>", value, "datetime01");
            return (Criteria) this;
        }

        public Criteria andDatetime01GreaterThan(LocalDateTime value) {
            addCriterion("datetime01 >", value, "datetime01");
            return (Criteria) this;
        }

        public Criteria andDatetime01GreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("datetime01 >=", value, "datetime01");
            return (Criteria) this;
        }

        public Criteria andDatetime01LessThan(LocalDateTime value) {
            addCriterion("datetime01 <", value, "datetime01");
            return (Criteria) this;
        }

        public Criteria andDatetime01LessThanOrEqualTo(LocalDateTime value) {
            addCriterion("datetime01 <=", value, "datetime01");
            return (Criteria) this;
        }

        public Criteria andDatetime01In(List<LocalDateTime> values) {
            addCriterion("datetime01 in", values, "datetime01");
            return (Criteria) this;
        }

        public Criteria andDatetime01NotIn(List<LocalDateTime> values) {
            addCriterion("datetime01 not in", values, "datetime01");
            return (Criteria) this;
        }

        public Criteria andDatetime01Between(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("datetime01 between", value1, value2, "datetime01");
            return (Criteria) this;
        }

        public Criteria andDatetime01NotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("datetime01 not between", value1, value2, "datetime01");
            return (Criteria) this;
        }

        public Criteria andRadio01IsNull() {
            addCriterion("radio01 is null");
            return (Criteria) this;
        }

        public Criteria andRadio01IsNotNull() {
            addCriterion("radio01 is not null");
            return (Criteria) this;
        }

        public Criteria andRadio01EqualTo(Boolean value) {
            addCriterion("radio01 =", value, "radio01");
            return (Criteria) this;
        }

        public Criteria andRadio01NotEqualTo(Boolean value) {
            addCriterion("radio01 <>", value, "radio01");
            return (Criteria) this;
        }

        public Criteria andRadio01GreaterThan(Boolean value) {
            addCriterion("radio01 >", value, "radio01");
            return (Criteria) this;
        }

        public Criteria andRadio01GreaterThanOrEqualTo(Boolean value) {
            addCriterion("radio01 >=", value, "radio01");
            return (Criteria) this;
        }

        public Criteria andRadio01LessThan(Boolean value) {
            addCriterion("radio01 <", value, "radio01");
            return (Criteria) this;
        }

        public Criteria andRadio01LessThanOrEqualTo(Boolean value) {
            addCriterion("radio01 <=", value, "radio01");
            return (Criteria) this;
        }

        public Criteria andRadio01In(List<Boolean> values) {
            addCriterion("radio01 in", values, "radio01");
            return (Criteria) this;
        }

        public Criteria andRadio01NotIn(List<Boolean> values) {
            addCriterion("radio01 not in", values, "radio01");
            return (Criteria) this;
        }

        public Criteria andRadio01Between(Boolean value1, Boolean value2) {
            addCriterion("radio01 between", value1, value2, "radio01");
            return (Criteria) this;
        }

        public Criteria andRadio01NotBetween(Boolean value1, Boolean value2) {
            addCriterion("radio01 not between", value1, value2, "radio01");
            return (Criteria) this;
        }

        public Criteria andRadio02IsNull() {
            addCriterion("radio02 is null");
            return (Criteria) this;
        }

        public Criteria andRadio02IsNotNull() {
            addCriterion("radio02 is not null");
            return (Criteria) this;
        }

        public Criteria andRadio02EqualTo(String value) {
            addCriterion("radio02 =", value, "radio02");
            return (Criteria) this;
        }

        public Criteria andRadio02NotEqualTo(String value) {
            addCriterion("radio02 <>", value, "radio02");
            return (Criteria) this;
        }

        public Criteria andRadio02GreaterThan(String value) {
            addCriterion("radio02 >", value, "radio02");
            return (Criteria) this;
        }

        public Criteria andRadio02GreaterThanOrEqualTo(String value) {
            addCriterion("radio02 >=", value, "radio02");
            return (Criteria) this;
        }

        public Criteria andRadio02LessThan(String value) {
            addCriterion("radio02 <", value, "radio02");
            return (Criteria) this;
        }

        public Criteria andRadio02LessThanOrEqualTo(String value) {
            addCriterion("radio02 <=", value, "radio02");
            return (Criteria) this;
        }

        public Criteria andRadio02Like(String value) {
            addCriterion("radio02 like", value, "radio02");
            return (Criteria) this;
        }

        public Criteria andRadio02NotLike(String value) {
            addCriterion("radio02 not like", value, "radio02");
            return (Criteria) this;
        }

        public Criteria andRadio02In(List<String> values) {
            addCriterion("radio02 in", values, "radio02");
            return (Criteria) this;
        }

        public Criteria andRadio02NotIn(List<String> values) {
            addCriterion("radio02 not in", values, "radio02");
            return (Criteria) this;
        }

        public Criteria andRadio02Between(String value1, String value2) {
            addCriterion("radio02 between", value1, value2, "radio02");
            return (Criteria) this;
        }

        public Criteria andRadio02NotBetween(String value1, String value2) {
            addCriterion("radio02 not between", value1, value2, "radio02");
            return (Criteria) this;
        }

        public Criteria andSelect01IsNull() {
            addCriterion("select01 is null");
            return (Criteria) this;
        }

        public Criteria andSelect01IsNotNull() {
            addCriterion("select01 is not null");
            return (Criteria) this;
        }

        public Criteria andSelect01EqualTo(String value) {
            addCriterion("select01 =", value, "select01");
            return (Criteria) this;
        }

        public Criteria andSelect01NotEqualTo(String value) {
            addCriterion("select01 <>", value, "select01");
            return (Criteria) this;
        }

        public Criteria andSelect01GreaterThan(String value) {
            addCriterion("select01 >", value, "select01");
            return (Criteria) this;
        }

        public Criteria andSelect01GreaterThanOrEqualTo(String value) {
            addCriterion("select01 >=", value, "select01");
            return (Criteria) this;
        }

        public Criteria andSelect01LessThan(String value) {
            addCriterion("select01 <", value, "select01");
            return (Criteria) this;
        }

        public Criteria andSelect01LessThanOrEqualTo(String value) {
            addCriterion("select01 <=", value, "select01");
            return (Criteria) this;
        }

        public Criteria andSelect01Like(String value) {
            addCriterion("select01 like", value, "select01");
            return (Criteria) this;
        }

        public Criteria andSelect01NotLike(String value) {
            addCriterion("select01 not like", value, "select01");
            return (Criteria) this;
        }

        public Criteria andSelect01In(List<String> values) {
            addCriterion("select01 in", values, "select01");
            return (Criteria) this;
        }

        public Criteria andSelect01NotIn(List<String> values) {
            addCriterion("select01 not in", values, "select01");
            return (Criteria) this;
        }

        public Criteria andSelect01Between(String value1, String value2) {
            addCriterion("select01 between", value1, value2, "select01");
            return (Criteria) this;
        }

        public Criteria andSelect01NotBetween(String value1, String value2) {
            addCriterion("select01 not between", value1, value2, "select01");
            return (Criteria) this;
        }

        public Criteria andSelect03IsNull() {
            addCriterion("select03 is null");
            return (Criteria) this;
        }

        public Criteria andSelect03IsNotNull() {
            addCriterion("select03 is not null");
            return (Criteria) this;
        }

        public Criteria andSelect03EqualTo(String value) {
            addCriterion("select03 =", value, "select03");
            return (Criteria) this;
        }

        public Criteria andSelect03NotEqualTo(String value) {
            addCriterion("select03 <>", value, "select03");
            return (Criteria) this;
        }

        public Criteria andSelect03GreaterThan(String value) {
            addCriterion("select03 >", value, "select03");
            return (Criteria) this;
        }

        public Criteria andSelect03GreaterThanOrEqualTo(String value) {
            addCriterion("select03 >=", value, "select03");
            return (Criteria) this;
        }

        public Criteria andSelect03LessThan(String value) {
            addCriterion("select03 <", value, "select03");
            return (Criteria) this;
        }

        public Criteria andSelect03LessThanOrEqualTo(String value) {
            addCriterion("select03 <=", value, "select03");
            return (Criteria) this;
        }

        public Criteria andSelect03Like(String value) {
            addCriterion("select03 like", value, "select03");
            return (Criteria) this;
        }

        public Criteria andSelect03NotLike(String value) {
            addCriterion("select03 not like", value, "select03");
            return (Criteria) this;
        }

        public Criteria andSelect03In(List<String> values) {
            addCriterion("select03 in", values, "select03");
            return (Criteria) this;
        }

        public Criteria andSelect03NotIn(List<String> values) {
            addCriterion("select03 not in", values, "select03");
            return (Criteria) this;
        }

        public Criteria andSelect03Between(String value1, String value2) {
            addCriterion("select03 between", value1, value2, "select03");
            return (Criteria) this;
        }

        public Criteria andSelect03NotBetween(String value1, String value2) {
            addCriterion("select03 not between", value1, value2, "select03");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("status like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("status not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andText01IsNull() {
            addCriterion("text01 is null");
            return (Criteria) this;
        }

        public Criteria andText01IsNotNull() {
            addCriterion("text01 is not null");
            return (Criteria) this;
        }

        public Criteria andText01EqualTo(String value) {
            addCriterion("text01 =", value, "text01");
            return (Criteria) this;
        }

        public Criteria andText01NotEqualTo(String value) {
            addCriterion("text01 <>", value, "text01");
            return (Criteria) this;
        }

        public Criteria andText01GreaterThan(String value) {
            addCriterion("text01 >", value, "text01");
            return (Criteria) this;
        }

        public Criteria andText01GreaterThanOrEqualTo(String value) {
            addCriterion("text01 >=", value, "text01");
            return (Criteria) this;
        }

        public Criteria andText01LessThan(String value) {
            addCriterion("text01 <", value, "text01");
            return (Criteria) this;
        }

        public Criteria andText01LessThanOrEqualTo(String value) {
            addCriterion("text01 <=", value, "text01");
            return (Criteria) this;
        }

        public Criteria andText01Like(String value) {
            addCriterion("text01 like", value, "text01");
            return (Criteria) this;
        }

        public Criteria andText01NotLike(String value) {
            addCriterion("text01 not like", value, "text01");
            return (Criteria) this;
        }

        public Criteria andText01In(List<String> values) {
            addCriterion("text01 in", values, "text01");
            return (Criteria) this;
        }

        public Criteria andText01NotIn(List<String> values) {
            addCriterion("text01 not in", values, "text01");
            return (Criteria) this;
        }

        public Criteria andText01Between(String value1, String value2) {
            addCriterion("text01 between", value1, value2, "text01");
            return (Criteria) this;
        }

        public Criteria andText01NotBetween(String value1, String value2) {
            addCriterion("text01 not between", value1, value2, "text01");
            return (Criteria) this;
        }

        public Criteria andText02IsNull() {
            addCriterion("text02 is null");
            return (Criteria) this;
        }

        public Criteria andText02IsNotNull() {
            addCriterion("text02 is not null");
            return (Criteria) this;
        }

        public Criteria andText02EqualTo(Integer value) {
            addCriterion("text02 =", value, "text02");
            return (Criteria) this;
        }

        public Criteria andText02NotEqualTo(Integer value) {
            addCriterion("text02 <>", value, "text02");
            return (Criteria) this;
        }

        public Criteria andText02GreaterThan(Integer value) {
            addCriterion("text02 >", value, "text02");
            return (Criteria) this;
        }

        public Criteria andText02GreaterThanOrEqualTo(Integer value) {
            addCriterion("text02 >=", value, "text02");
            return (Criteria) this;
        }

        public Criteria andText02LessThan(Integer value) {
            addCriterion("text02 <", value, "text02");
            return (Criteria) this;
        }

        public Criteria andText02LessThanOrEqualTo(Integer value) {
            addCriterion("text02 <=", value, "text02");
            return (Criteria) this;
        }

        public Criteria andText02In(List<Integer> values) {
            addCriterion("text02 in", values, "text02");
            return (Criteria) this;
        }

        public Criteria andText02NotIn(List<Integer> values) {
            addCriterion("text02 not in", values, "text02");
            return (Criteria) this;
        }

        public Criteria andText02Between(Integer value1, Integer value2) {
            addCriterion("text02 between", value1, value2, "text02");
            return (Criteria) this;
        }

        public Criteria andText02NotBetween(Integer value1, Integer value2) {
            addCriterion("text02 not between", value1, value2, "text02");
            return (Criteria) this;
        }

        public Criteria andText03IsNull() {
            addCriterion("text03 is null");
            return (Criteria) this;
        }

        public Criteria andText03IsNotNull() {
            addCriterion("text03 is not null");
            return (Criteria) this;
        }

        public Criteria andText03EqualTo(Float value) {
            addCriterion("text03 =", value, "text03");
            return (Criteria) this;
        }

        public Criteria andText03NotEqualTo(Float value) {
            addCriterion("text03 <>", value, "text03");
            return (Criteria) this;
        }

        public Criteria andText03GreaterThan(Float value) {
            addCriterion("text03 >", value, "text03");
            return (Criteria) this;
        }

        public Criteria andText03GreaterThanOrEqualTo(Float value) {
            addCriterion("text03 >=", value, "text03");
            return (Criteria) this;
        }

        public Criteria andText03LessThan(Float value) {
            addCriterion("text03 <", value, "text03");
            return (Criteria) this;
        }

        public Criteria andText03LessThanOrEqualTo(Float value) {
            addCriterion("text03 <=", value, "text03");
            return (Criteria) this;
        }

        public Criteria andText03In(List<Float> values) {
            addCriterion("text03 in", values, "text03");
            return (Criteria) this;
        }

        public Criteria andText03NotIn(List<Float> values) {
            addCriterion("text03 not in", values, "text03");
            return (Criteria) this;
        }

        public Criteria andText03Between(Float value1, Float value2) {
            addCriterion("text03 between", value1, value2, "text03");
            return (Criteria) this;
        }

        public Criteria andText03NotBetween(Float value1, Float value2) {
            addCriterion("text03 not between", value1, value2, "text03");
            return (Criteria) this;
        }

        public Criteria andText04IsNull() {
            addCriterion("text04 is null");
            return (Criteria) this;
        }

        public Criteria andText04IsNotNull() {
            addCriterion("text04 is not null");
            return (Criteria) this;
        }

        public Criteria andText04EqualTo(Boolean value) {
            addCriterion("text04 =", value, "text04");
            return (Criteria) this;
        }

        public Criteria andText04NotEqualTo(Boolean value) {
            addCriterion("text04 <>", value, "text04");
            return (Criteria) this;
        }

        public Criteria andText04GreaterThan(Boolean value) {
            addCriterion("text04 >", value, "text04");
            return (Criteria) this;
        }

        public Criteria andText04GreaterThanOrEqualTo(Boolean value) {
            addCriterion("text04 >=", value, "text04");
            return (Criteria) this;
        }

        public Criteria andText04LessThan(Boolean value) {
            addCriterion("text04 <", value, "text04");
            return (Criteria) this;
        }

        public Criteria andText04LessThanOrEqualTo(Boolean value) {
            addCriterion("text04 <=", value, "text04");
            return (Criteria) this;
        }

        public Criteria andText04In(List<Boolean> values) {
            addCriterion("text04 in", values, "text04");
            return (Criteria) this;
        }

        public Criteria andText04NotIn(List<Boolean> values) {
            addCriterion("text04 not in", values, "text04");
            return (Criteria) this;
        }

        public Criteria andText04Between(Boolean value1, Boolean value2) {
            addCriterion("text04 between", value1, value2, "text04");
            return (Criteria) this;
        }

        public Criteria andText04NotBetween(Boolean value1, Boolean value2) {
            addCriterion("text04 not between", value1, value2, "text04");
            return (Criteria) this;
        }

        public Criteria andTextarea01IsNull() {
            addCriterion("textarea01 is null");
            return (Criteria) this;
        }

        public Criteria andTextarea01IsNotNull() {
            addCriterion("textarea01 is not null");
            return (Criteria) this;
        }

        public Criteria andTextarea01EqualTo(String value) {
            addCriterion("textarea01 =", value, "textarea01");
            return (Criteria) this;
        }

        public Criteria andTextarea01NotEqualTo(String value) {
            addCriterion("textarea01 <>", value, "textarea01");
            return (Criteria) this;
        }

        public Criteria andTextarea01GreaterThan(String value) {
            addCriterion("textarea01 >", value, "textarea01");
            return (Criteria) this;
        }

        public Criteria andTextarea01GreaterThanOrEqualTo(String value) {
            addCriterion("textarea01 >=", value, "textarea01");
            return (Criteria) this;
        }

        public Criteria andTextarea01LessThan(String value) {
            addCriterion("textarea01 <", value, "textarea01");
            return (Criteria) this;
        }

        public Criteria andTextarea01LessThanOrEqualTo(String value) {
            addCriterion("textarea01 <=", value, "textarea01");
            return (Criteria) this;
        }

        public Criteria andTextarea01Like(String value) {
            addCriterion("textarea01 like", value, "textarea01");
            return (Criteria) this;
        }

        public Criteria andTextarea01NotLike(String value) {
            addCriterion("textarea01 not like", value, "textarea01");
            return (Criteria) this;
        }

        public Criteria andTextarea01In(List<String> values) {
            addCriterion("textarea01 in", values, "textarea01");
            return (Criteria) this;
        }

        public Criteria andTextarea01NotIn(List<String> values) {
            addCriterion("textarea01 not in", values, "textarea01");
            return (Criteria) this;
        }

        public Criteria andTextarea01Between(String value1, String value2) {
            addCriterion("textarea01 between", value1, value2, "textarea01");
            return (Criteria) this;
        }

        public Criteria andTextarea01NotBetween(String value1, String value2) {
            addCriterion("textarea01 not between", value1, value2, "textarea01");
            return (Criteria) this;
        }

        public Criteria andCreatedByLikeInsensitive(String value) {
            addCriterion("upper(created_by) like", value.toUpperCase(), "createdBy");
            return (Criteria) this;
        }

        public Criteria andLastModifiedByLikeInsensitive(String value) {
            addCriterion("upper(last_modified_by) like", value.toUpperCase(), "lastModifiedBy");
            return (Criteria) this;
        }

        public Criteria andAttachedFile01uuidLikeInsensitive(String value) {
            addCriterion("upper(attached_file01uuid) like", value.toUpperCase(), "attachedFile01uuid");
            return (Criteria) this;
        }

        public Criteria andCheckbox01LikeInsensitive(String value) {
            addCriterion("upper(checkbox01) like", value.toUpperCase(), "checkbox01");
            return (Criteria) this;
        }

        public Criteria andCombobox01LikeInsensitive(String value) {
            addCriterion("upper(combobox01) like", value.toUpperCase(), "combobox01");
            return (Criteria) this;
        }

        public Criteria andCombobox02LikeInsensitive(String value) {
            addCriterion("upper(combobox02) like", value.toUpperCase(), "combobox02");
            return (Criteria) this;
        }

        public Criteria andRadio02LikeInsensitive(String value) {
            addCriterion("upper(radio02) like", value.toUpperCase(), "radio02");
            return (Criteria) this;
        }

        public Criteria andSelect01LikeInsensitive(String value) {
            addCriterion("upper(select01) like", value.toUpperCase(), "select01");
            return (Criteria) this;
        }

        public Criteria andSelect03LikeInsensitive(String value) {
            addCriterion("upper(select03) like", value.toUpperCase(), "select03");
            return (Criteria) this;
        }

        public Criteria andStatusLikeInsensitive(String value) {
            addCriterion("upper(status) like", value.toUpperCase(), "status");
            return (Criteria) this;
        }

        public Criteria andText01LikeInsensitive(String value) {
            addCriterion("upper(text01) like", value.toUpperCase(), "text01");
            return (Criteria) this;
        }

        public Criteria andTextarea01LikeInsensitive(String value) {
            addCriterion("upper(textarea01) like", value.toUpperCase(), "textarea01");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table simple_entity
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}