package jp.co.stnet.cms.base.domain.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.time.LocalDateTime;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
 * Database Table Remarks:
 *   ユーザアカウント
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cms.account
 */
@Data
@EqualsAndHashCode
@Builder
@ToString
public class Account implements Serializable, StatusInterface<String> {
    /**
     * Database Column Remarks:
     *   ユーザ名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.version
     *
     * @mbg.generated
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.created_by
     *
     * @mbg.generated
     */
    private String createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.created_date
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy/MM/dd HH:mm:ss")
    private LocalDateTime createdDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.last_modified_by
     *
     * @mbg.generated
     */
    private String lastModifiedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.last_modified_date
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy/MM/dd HH:mm:ss")
    private LocalDateTime lastModifiedDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.allowed_ip
     *
     * @mbg.generated
     */
    private String allowedIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.api_key
     *
     * @mbg.generated
     */
    private String apiKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.department
     *
     * @mbg.generated
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.first_name
     *
     * @mbg.generated
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.image_uuid
     *
     * @mbg.generated
     */
    private String imageUuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.last_name
     *
     * @mbg.generated
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.profile
     *
     * @mbg.generated
     */
    private String profile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms.account.url
     *
     * @mbg.generated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms.account
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public String getId() {
        return username;
    }
}