package jp.co.stnet.cms.example.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.example.domain.model.mbg.LineItem;
import jp.co.stnet.cms.example.domain.model.mbg.LineItemExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface LineItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_line_items
     *
     * @mbg.generated
     */
    long countByExample(LineItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_line_items
     *
     * @mbg.generated
     */
    int deleteByExample(LineItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_line_items
     *
     * @mbg.generated
     */
    int insert(LineItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_line_items
     *
     * @mbg.generated
     */
    int insertSelective(LineItem row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_line_items
     *
     * @mbg.generated
     */
    List<LineItem> selectByExampleWithRowbounds(LineItemExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_line_items
     *
     * @mbg.generated
     */
    List<LineItem> selectByExample(LineItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_line_items
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") LineItem row, @Param("example") LineItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_line_items
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") LineItem row, @Param("example") LineItemExample example);
}