package jp.co.stnet.cms.example.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.example.domain.model.mbg.SimpleEntityRevision;
import jp.co.stnet.cms.example.domain.model.mbg.SimpleEntityRevisionExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface SimpleEntityRevisionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_revision
     *
     * @mbg.generated
     */
    long countByExample(SimpleEntityRevisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_revision
     *
     * @mbg.generated
     */
    int deleteByExample(SimpleEntityRevisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_revision
     *
     * @mbg.generated
     */
    int deleteByPrimaryKeyAndVersion(@Param("rid") Long rid, @Param("version") Long version);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_revision
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_revision
     *
     * @mbg.generated
     */
    int insert(SimpleEntityRevision row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_revision
     *
     * @mbg.generated
     */
    int insertSelective(SimpleEntityRevision row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_revision
     *
     * @mbg.generated
     */
    List<SimpleEntityRevision> selectByExampleWithRowbounds(SimpleEntityRevisionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_revision
     *
     * @mbg.generated
     */
    List<SimpleEntityRevision> selectByExample(SimpleEntityRevisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_revision
     *
     * @mbg.generated
     */
    SimpleEntityRevision selectByPrimaryKey(Long rid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_revision
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SimpleEntityRevision row, @Param("example") SimpleEntityRevisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_revision
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SimpleEntityRevision row, @Param("example") SimpleEntityRevisionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_revision
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersionSelective(SimpleEntityRevision row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_revision
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SimpleEntityRevision row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_revision
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersion(SimpleEntityRevision row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_revision
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SimpleEntityRevision row);
}