package jp.co.stnet.cms.example.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.example.domain.model.mbg.SimpleEntityText05;
import jp.co.stnet.cms.example.domain.model.mbg.SimpleEntityText05Example;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface SimpleEntityText05Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_text05
     *
     * @mbg.generated
     */
    long countByExample(SimpleEntityText05Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_text05
     *
     * @mbg.generated
     */
    int deleteByExample(SimpleEntityText05Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_text05
     *
     * @mbg.generated
     */
    int insert(SimpleEntityText05 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_text05
     *
     * @mbg.generated
     */
    int insertSelective(SimpleEntityText05 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_text05
     *
     * @mbg.generated
     */
    List<SimpleEntityText05> selectByExampleWithRowbounds(SimpleEntityText05Example example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_text05
     *
     * @mbg.generated
     */
    List<SimpleEntityText05> selectByExample(SimpleEntityText05Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_text05
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SimpleEntityText05 row, @Param("example") SimpleEntityText05Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_text05
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SimpleEntityText05 row, @Param("example") SimpleEntityText05Example example);
}