package jp.co.stnet.cms.example.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.example.domain.model.mbg.SimpleEntityCombobox03;
import jp.co.stnet.cms.example.domain.model.mbg.SimpleEntityCombobox03Example;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface SimpleEntityCombobox03Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_combobox03
     *
     * @mbg.generated
     */
    long countByExample(SimpleEntityCombobox03Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_combobox03
     *
     * @mbg.generated
     */
    int deleteByExample(SimpleEntityCombobox03Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_combobox03
     *
     * @mbg.generated
     */
    int insert(SimpleEntityCombobox03 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_combobox03
     *
     * @mbg.generated
     */
    int insertSelective(SimpleEntityCombobox03 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_combobox03
     *
     * @mbg.generated
     */
    List<SimpleEntityCombobox03> selectByExampleWithRowbounds(SimpleEntityCombobox03Example example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_combobox03
     *
     * @mbg.generated
     */
    List<SimpleEntityCombobox03> selectByExample(SimpleEntityCombobox03Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_combobox03
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SimpleEntityCombobox03 row, @Param("example") SimpleEntityCombobox03Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_combobox03
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SimpleEntityCombobox03 row, @Param("example") SimpleEntityCombobox03Example example);
}