package jp.co.stnet.cms.example.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.example.domain.model.mbg.SimpleEntitySelect02;
import jp.co.stnet.cms.example.domain.model.mbg.SimpleEntitySelect02Example;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface SimpleEntitySelect02Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_select02
     *
     * @mbg.generated
     */
    long countByExample(SimpleEntitySelect02Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_select02
     *
     * @mbg.generated
     */
    int deleteByExample(SimpleEntitySelect02Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_select02
     *
     * @mbg.generated
     */
    int insert(SimpleEntitySelect02 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_select02
     *
     * @mbg.generated
     */
    int insertSelective(SimpleEntitySelect02 row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_select02
     *
     * @mbg.generated
     */
    List<SimpleEntitySelect02> selectByExampleWithRowbounds(SimpleEntitySelect02Example example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_select02
     *
     * @mbg.generated
     */
    List<SimpleEntitySelect02> selectByExample(SimpleEntitySelect02Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_select02
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") SimpleEntitySelect02 row, @Param("example") SimpleEntitySelect02Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity_select02
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") SimpleEntitySelect02 row, @Param("example") SimpleEntitySelect02Example example);
}