package jp.co.stnet.cms.example.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.base.infrastructure.mapper.VersionMapperInterface;
import jp.co.stnet.cms.example.domain.model.mbg.TSimpleEntity;
import jp.co.stnet.cms.example.domain.model.mbg.TSimpleEntityExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface TSimpleEntityMapper extends VersionMapperInterface<TSimpleEntity, TSimpleEntityExample, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    long countByExample(TSimpleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    int deleteByExample(TSimpleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKeyAndVersion(@Param("id") Long id, @Param("version") Long version);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    int insert(TSimpleEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    int insertSelective(TSimpleEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    List<TSimpleEntity> selectByExampleWithRowbounds(TSimpleEntityExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    List<TSimpleEntity> selectByExample(TSimpleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    TSimpleEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TSimpleEntity row, @Param("example") TSimpleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TSimpleEntity row, @Param("example") TSimpleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersionSelective(@Param("row") TSimpleEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TSimpleEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersion(@Param("row") TSimpleEntity row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table simple_entity
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TSimpleEntity row);
}