package jp.co.stnet.cms.example.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.example.domain.model.mbg.VSimpleEntity;
import jp.co.stnet.cms.example.domain.model.mbg.VSimpleEntityExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface VSimpleEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_simple_entity
     *
     * @mbg.generated
     */
    long countByExample(VSimpleEntityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_simple_entity
     *
     * @mbg.generated
     */
    List<VSimpleEntity> selectByExampleWithRowbounds(VSimpleEntityExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_simple_entity
     *
     * @mbg.generated
     */
    List<VSimpleEntity> selectByExample(VSimpleEntityExample example);
}