package jp.co.stnet.cms.equipment.domain.model.mbg;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.time.LocalDateTime;
import jp.co.stnet.cms.base.domain.model.KeyInterface;
import jp.co.stnet.cms.base.domain.model.VersionInterface;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

/**
 * Database Table Remarks:
 *   承認フロー
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table approval_flow
 */
@Data
@SuperBuilder
@EqualsAndHashCode
@AllArgsConstructor
@ToString
@NoArgsConstructor
public class ApprovalFlow implements Serializable, KeyInterface<Long>, VersionInterface {
    /**
     * Database Column Remarks:
     *   承認フローID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_flow.approval_flow_id
     *
     * @mbg.generated
     */
    private Long approvalFlowId;

    /**
     * Database Column Remarks:
     *   作成者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_flow.created_by
     *
     * @mbg.generated
     */
    @EqualsAndHashCode.Exclude
    private String createdBy;

    /**
     * Database Column Remarks:
     *   作成日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_flow.created_date
     *
     * @mbg.generated
     */
    @EqualsAndHashCode.Exclude
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy/MM/dd HH:mm:ss")
    private LocalDateTime createdDate;

    /**
     * Database Column Remarks:
     *   最終更新者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_flow.last_modified_by
     *
     * @mbg.generated
     */
    @EqualsAndHashCode.Exclude
    private String lastModifiedBy;

    /**
     * Database Column Remarks:
     *   最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_flow.last_modified_date
     *
     * @mbg.generated
     */
    @EqualsAndHashCode.Exclude
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy/MM/dd HH:mm:ss")
    private LocalDateTime lastModifiedDate;

    /**
     * Database Column Remarks:
     *   バージョン(排他制御用)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_flow.version
     *
     * @mbg.generated
     */
    @EqualsAndHashCode.Exclude
    private Long version;

    /**
     * Database Column Remarks:
     *   第１承認者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_flow.fist_approver
     *
     * @mbg.generated
     */
    private String fistApprover;

    /**
     * Database Column Remarks:
     *   第２承認者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval_flow.second_approver
     *
     * @mbg.generated
     */
    private String secondApprover;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table approval_flow
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return approvalFlowId;
    }
}