package jp.co.stnet.cms.equipment.domain.model.mbg;

import com.fasterxml.jackson.annotation.JsonFormat;
import java.io.Serializable;
import java.time.LocalDate;
import java.time.LocalDateTime;
import jp.co.stnet.cms.base.domain.model.KeyInterface;
import jp.co.stnet.cms.base.domain.model.VersionInterface;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;
import lombok.ToString;
import lombok.experimental.SuperBuilder;

/**
 * Database Table Remarks:
 *   棚卸し履歴
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table confirm_history
 */
@Data
@SuperBuilder
@EqualsAndHashCode
@AllArgsConstructor
@ToString
@NoArgsConstructor
public class ConfirmHistory implements Serializable, KeyInterface<Long>, VersionInterface {
    /**
     * Database Column Remarks:
     *   棚卸し履歴ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confirm_history.confirm_id
     *
     * @mbg.generated
     */
    private Long confirmId;

    /**
     * Database Column Remarks:
     *   作成者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confirm_history.created_by
     *
     * @mbg.generated
     */
    @EqualsAndHashCode.Exclude
    private String createdBy;

    /**
     * Database Column Remarks:
     *   作成日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confirm_history.created_date
     *
     * @mbg.generated
     */
    @EqualsAndHashCode.Exclude
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy/MM/dd HH:mm:ss")
    private LocalDateTime createdDate;

    /**
     * Database Column Remarks:
     *   最終更新者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confirm_history.last_modified_by
     *
     * @mbg.generated
     */
    @EqualsAndHashCode.Exclude
    private String lastModifiedBy;

    /**
     * Database Column Remarks:
     *   最終更新日時
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confirm_history.last_modified_date
     *
     * @mbg.generated
     */
    @EqualsAndHashCode.Exclude
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy/MM/dd HH:mm:ss")
    private LocalDateTime lastModifiedDate;

    /**
     * Database Column Remarks:
     *   バージョン(排他制御用)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confirm_history.version
     *
     * @mbg.generated
     */
    @EqualsAndHashCode.Exclude
    private Long version;

    /**
     * Database Column Remarks:
     *   確認ステータス
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confirm_history.check_status
     *
     * @mbg.generated
     */
    private String checkStatus;

    /**
     * Database Column Remarks:
     *   確認日
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confirm_history.execute_date
     *
     * @mbg.generated
     */
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy/MM/dd")
    private LocalDate executeDate;

    /**
     * Database Column Remarks:
     *   備品ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confirm_history.equip_id
     *
     * @mbg.generated
     */
    private Long equipId;

    /**
     * Database Column Remarks:
     *   確認者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column confirm_history.execute_by
     *
     * @mbg.generated
     */
    private String executeBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table confirm_history
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    public Long getId() {
        return confirmId;
    }
}