package jp.co.stnet.cms.base.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.base.domain.model.mbg.EmailChangeRequest;
import jp.co.stnet.cms.base.domain.model.mbg.EmailChangeRequestExample;
import jp.co.stnet.cms.base.infrastructure.mapper.MapperInterface;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface EmailChangeRequestMapper extends MapperInterface<EmailChangeRequest, EmailChangeRequestExample, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_change_request
     *
     * @mbg.generated
     */
    long countByExample(EmailChangeRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_change_request
     *
     * @mbg.generated
     */
    int deleteByExample(EmailChangeRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_change_request
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String token);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_change_request
     *
     * @mbg.generated
     */
    int insert(EmailChangeRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_change_request
     *
     * @mbg.generated
     */
    int insertSelective(EmailChangeRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_change_request
     *
     * @mbg.generated
     */
    List<EmailChangeRequest> selectByExampleWithRowbounds(EmailChangeRequestExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_change_request
     *
     * @mbg.generated
     */
    List<EmailChangeRequest> selectByExample(EmailChangeRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_change_request
     *
     * @mbg.generated
     */
    EmailChangeRequest selectByPrimaryKey(String token);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_change_request
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") EmailChangeRequest row, @Param("example") EmailChangeRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_change_request
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") EmailChangeRequest row, @Param("example") EmailChangeRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_change_request
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(EmailChangeRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_change_request
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EmailChangeRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_change_request
     *
     * @mbg.generated
     */
    int merge(EmailChangeRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_email_change_request
     *
     * @mbg.generated
     */
    void truncate();
}