package jp.co.stnet.cms.base.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.base.domain.model.mbg.FailedEmailChangeRequest;
import jp.co.stnet.cms.base.domain.model.mbg.FailedEmailChangeRequestExample;
import jp.co.stnet.cms.base.domain.model.mbg.FailedEmailChangeRequestKey;
import jp.co.stnet.cms.base.infrastructure.mapper.MapperInterface;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface FailedEmailChangeRequestMapper extends MapperInterface<FailedEmailChangeRequest, FailedEmailChangeRequestExample, FailedEmailChangeRequestKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_failed_email_change_request
     *
     * @mbg.generated
     */
    long countByExample(FailedEmailChangeRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_failed_email_change_request
     *
     * @mbg.generated
     */
    int deleteByExample(FailedEmailChangeRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_failed_email_change_request
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(FailedEmailChangeRequestKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_failed_email_change_request
     *
     * @mbg.generated
     */
    int insert(FailedEmailChangeRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_failed_email_change_request
     *
     * @mbg.generated
     */
    int insertSelective(FailedEmailChangeRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_failed_email_change_request
     *
     * @mbg.generated
     */
    List<FailedEmailChangeRequest> selectByExampleWithRowbounds(FailedEmailChangeRequestExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_failed_email_change_request
     *
     * @mbg.generated
     */
    List<FailedEmailChangeRequest> selectByExample(FailedEmailChangeRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_failed_email_change_request
     *
     * @mbg.generated
     */
    FailedEmailChangeRequest selectByPrimaryKey(FailedEmailChangeRequestKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_failed_email_change_request
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") FailedEmailChangeRequest row, @Param("example") FailedEmailChangeRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_failed_email_change_request
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") FailedEmailChangeRequest row, @Param("example") FailedEmailChangeRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_failed_email_change_request
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FailedEmailChangeRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_failed_email_change_request
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FailedEmailChangeRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_failed_email_change_request
     *
     * @mbg.generated
     */
    int merge(FailedEmailChangeRequest row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_failed_email_change_request
     *
     * @mbg.generated
     */
    void truncate();
}