package jp.co.stnet.cms.base.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.base.domain.model.mbg.FileManaged;
import jp.co.stnet.cms.base.domain.model.mbg.FileManagedExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface FileManagedMapper extends jp.co.stnet.cms.base.infrastructure.mapper.VersionMapperInterface<FileManaged, FileManagedExample, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_managed
     *
     * @mbg.generated
     */
    @Override
    long countByExample(FileManagedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_managed
     *
     * @mbg.generated
     */
    @Override
    int deleteByExample(FileManagedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_managed
     *
     * @mbg.generated
     */
    @Override
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_managed
     *
     * @mbg.generated
     */
    @Override
    int insert(FileManaged row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_managed
     *
     * @mbg.generated
     */
    @Override
    int insertSelective(FileManaged row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_managed
     *
     * @mbg.generated
     */
    List<FileManaged> selectByExampleWithRowbounds(FileManagedExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_managed
     *
     * @mbg.generated
     */
    @Override
    List<FileManaged> selectByExample(FileManagedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_managed
     *
     * @mbg.generated
     */
    @Override
    FileManaged selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_managed
     *
     * @mbg.generated
     */
    @Override
    int updateByExampleSelective(@Param("row") FileManaged row, @Param("example") FileManagedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_managed
     *
     * @mbg.generated
     */
    @Override
    int updateByExample(@Param("row") FileManaged row, @Param("example") FileManagedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_managed
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersionSelective(FileManaged row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_managed
     *
     * @mbg.generated
     */
    @Override
    int updateByPrimaryKeySelective(FileManaged row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_managed
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersion(FileManaged row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_managed
     *
     * @mbg.generated
     */
    @Override
    int updateByPrimaryKey(FileManaged row);
}