package jp.co.stnet.cms.base.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.base.domain.model.mbg.FileManaged;
import jp.co.stnet.cms.base.domain.model.mbg.FileManagedExample;
import jp.co.stnet.cms.base.infrastructure.mapper.MapperInterface;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface FileManagedMapper extends MapperInterface<FileManaged, FileManagedExample, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_managed
     *
     * @mbg.generated
     */
    long countByExample(FileManagedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_managed
     *
     * @mbg.generated
     */
    int deleteByExample(FileManagedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_managed
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_managed
     *
     * @mbg.generated
     */
    int insert(FileManaged row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_managed
     *
     * @mbg.generated
     */
    int insertSelective(FileManaged row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_managed
     *
     * @mbg.generated
     */
    List<FileManaged> selectByExampleWithRowbounds(FileManagedExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_managed
     *
     * @mbg.generated
     */
    List<FileManaged> selectByExample(FileManagedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_managed
     *
     * @mbg.generated
     */
    FileManaged selectByPrimaryKey(String uuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_managed
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") FileManaged row, @Param("example") FileManagedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_managed
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") FileManaged row, @Param("example") FileManagedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_managed
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FileManaged row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_managed
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FileManaged row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_managed
     *
     * @mbg.generated
     */
    int merge(FileManaged row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_file_managed
     *
     * @mbg.generated
     */
    void truncate();
}