package jp.co.stnet.cms.base.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.base.domain.model.mbg.PasswordReissueInfo;
import jp.co.stnet.cms.base.domain.model.mbg.PasswordReissueInfoExample;
import jp.co.stnet.cms.base.infrastructure.mapper.MapperInterface;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface PasswordReissueInfoMapper extends MapperInterface<PasswordReissueInfo, PasswordReissueInfoExample, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_reissue_info
     *
     * @mbg.generated
     */
    long countByExample(PasswordReissueInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_reissue_info
     *
     * @mbg.generated
     */
    int deleteByExample(PasswordReissueInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_reissue_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String token);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_reissue_info
     *
     * @mbg.generated
     */
    int insert(PasswordReissueInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_reissue_info
     *
     * @mbg.generated
     */
    int insertSelective(PasswordReissueInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_reissue_info
     *
     * @mbg.generated
     */
    List<PasswordReissueInfo> selectByExampleWithRowbounds(PasswordReissueInfoExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_reissue_info
     *
     * @mbg.generated
     */
    List<PasswordReissueInfo> selectByExample(PasswordReissueInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_reissue_info
     *
     * @mbg.generated
     */
    PasswordReissueInfo selectByPrimaryKey(String token);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_reissue_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") PasswordReissueInfo row, @Param("example") PasswordReissueInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_reissue_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") PasswordReissueInfo row, @Param("example") PasswordReissueInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_reissue_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PasswordReissueInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_reissue_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PasswordReissueInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_reissue_info
     *
     * @mbg.generated
     */
    int merge(PasswordReissueInfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_reissue_info
     *
     * @mbg.generated
     */
    void truncate();
}