package jp.co.stnet.cms.base.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.base.domain.model.mbg.PasswordHistory;
import jp.co.stnet.cms.base.domain.model.mbg.PasswordHistoryExample;
import jp.co.stnet.cms.base.domain.model.mbg.PasswordHistoryKey;
import jp.co.stnet.cms.base.infrastructure.mapper.MapperInterface;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface PasswordHistoryMapper extends MapperInterface<PasswordHistory, PasswordHistoryExample, PasswordHistoryKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_history
     *
     * @mbg.generated
     */
    long countByExample(PasswordHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_history
     *
     * @mbg.generated
     */
    int deleteByExample(PasswordHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(PasswordHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_history
     *
     * @mbg.generated
     */
    int insert(PasswordHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_history
     *
     * @mbg.generated
     */
    int insertSelective(PasswordHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_history
     *
     * @mbg.generated
     */
    List<PasswordHistory> selectByExampleWithRowbounds(PasswordHistoryExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_history
     *
     * @mbg.generated
     */
    List<PasswordHistory> selectByExample(PasswordHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_history
     *
     * @mbg.generated
     */
    PasswordHistory selectByPrimaryKey(PasswordHistoryKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") PasswordHistory row, @Param("example") PasswordHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") PasswordHistory row, @Param("example") PasswordHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PasswordHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PasswordHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_history
     *
     * @mbg.generated
     */
    int merge(PasswordHistory row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_password_history
     *
     * @mbg.generated
     */
    void truncate();
}