package jp.co.stnet.cms.base.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.base.domain.model.mbg.PermissionRole;
import jp.co.stnet.cms.base.domain.model.mbg.PermissionRoleExample;
import jp.co.stnet.cms.base.domain.model.mbg.PermissionRoleKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface PermissionRoleMapper extends jp.co.stnet.cms.base.infrastructure.mapper.MapperInterface<PermissionRole, PermissionRoleExample, PermissionRoleKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbg.generated
     */
    @Override
    long countByExample(PermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbg.generated
     */
    @Override
    int deleteByExample(PermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbg.generated
     */
    @Override
    int deleteByPrimaryKey(PermissionRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbg.generated
     */
    @Override
    int insert(PermissionRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbg.generated
     */
    @Override
    int insertSelective(PermissionRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbg.generated
     */
    List<PermissionRole> selectByExampleWithRowbounds(PermissionRoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbg.generated
     */
    @Override
    List<PermissionRole> selectByExample(PermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbg.generated
     */
    @Override
    PermissionRole selectByPrimaryKey(PermissionRoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbg.generated
     */
    @Override
    int updateByExampleSelective(@Param("row") PermissionRole row, @Param("example") PermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbg.generated
     */
    @Override
    int updateByExample(@Param("row") PermissionRole row, @Param("example") PermissionRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersionSelective(PermissionRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbg.generated
     */
    @Override
    int updateByPrimaryKeySelective(PermissionRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersion(PermissionRole row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table permission_role
     *
     * @mbg.generated
     */
    @Override
    int updateByPrimaryKey(PermissionRole row);
}