package jp.co.stnet.cms.base.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.base.domain.model.mbg.Role;
import jp.co.stnet.cms.base.domain.model.mbg.RoleExample;
import jp.co.stnet.cms.base.domain.model.mbg.RoleKey;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface RoleMapper extends jp.co.stnet.cms.base.infrastructure.mapper.MapperInterface<Role, RoleExample, RoleKey> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.role
     *
     * @mbg.generated
     */
    @Override
    long countByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.role
     *
     * @mbg.generated
     */
    @Override
    int deleteByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.role
     *
     * @mbg.generated
     */
    int deleteByPrimaryKeyAndVersion(RoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.role
     *
     * @mbg.generated
     */
    @Override
    int deleteByPrimaryKey(RoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.role
     *
     * @mbg.generated
     */
    @Override
    int insert(Role row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.role
     *
     * @mbg.generated
     */
    @Override
    int insertSelective(Role row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.role
     *
     * @mbg.generated
     */
    List<Role> selectByExampleWithRowbounds(RoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.role
     *
     * @mbg.generated
     */
    @Override
    List<Role> selectByExample(RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.role
     *
     * @mbg.generated
     */
    @Override
    Role selectByPrimaryKey(RoleKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.role
     *
     * @mbg.generated
     */
    @Override
    int updateByExampleSelective(@Param("row") Role row, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.role
     *
     * @mbg.generated
     */
    @Override
    int updateByExample(@Param("row") Role row, @Param("example") RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersionSelective(Role row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.role
     *
     * @mbg.generated
     */
    @Override
    int updateByPrimaryKeySelective(Role row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.role
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersion(Role row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms.role
     *
     * @mbg.generated
     */
    @Override
    int updateByPrimaryKey(Role row);
}