package jp.co.stnet.cms.base.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.base.domain.model.mbg.TempFile;
import jp.co.stnet.cms.base.domain.model.mbg.TempFileExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface TempFileMapper extends jp.co.stnet.cms.base.infrastructure.mapper.MapperInterface<TempFile, TempFileExample, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_file
     *
     * @mbg.generated
     */
    @Override
    long countByExample(TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_file
     *
     * @mbg.generated
     */
    @Override
    int deleteByExample(TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_file
     *
     * @mbg.generated
     */
    @Override
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_file
     *
     * @mbg.generated
     */
    @Override
    int insert(TempFile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_file
     *
     * @mbg.generated
     */
    @Override
    int insertSelective(TempFile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_file
     *
     * @mbg.generated
     */
    List<TempFile> selectByExampleWithRowbounds(TempFileExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_file
     *
     * @mbg.generated
     */
    @Override
    List<TempFile> selectByExample(TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_file
     *
     * @mbg.generated
     */
    @Override
    TempFile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_file
     *
     * @mbg.generated
     */
    @Override
    int updateByExampleSelective(@Param("row") TempFile row, @Param("example") TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_file
     *
     * @mbg.generated
     */
    @Override
    int updateByExample(@Param("row") TempFile row, @Param("example") TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersionSelective(TempFile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_file
     *
     * @mbg.generated
     */
    @Override
    int updateByPrimaryKeySelective(TempFile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersion(TempFile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_file
     *
     * @mbg.generated
     */
    @Override
    int updateByPrimaryKey(TempFile row);
}