package jp.co.stnet.cms.base.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.base.domain.model.mbg.TempFile;
import jp.co.stnet.cms.base.domain.model.mbg.TempFileExample;
import jp.co.stnet.cms.base.infrastructure.mapper.MapperInterface;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface TempFileMapper extends MapperInterface<TempFile, TempFileExample, String> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_file
     *
     * @mbg.generated
     */
    long countByExample(TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_file
     *
     * @mbg.generated
     */
    int deleteByExample(TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_file
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_file
     *
     * @mbg.generated
     */
    int insert(TempFile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_file
     *
     * @mbg.generated
     */
    int insertSelective(TempFile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_file
     *
     * @mbg.generated
     */
    List<TempFile> selectByExampleWithBLOBsWithRowbounds(TempFileExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_file
     *
     * @mbg.generated
     */
    List<TempFile> selectByExampleWithBLOBs(TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_file
     *
     * @mbg.generated
     */
    List<TempFile> selectByExampleWithRowbounds(TempFileExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_file
     *
     * @mbg.generated
     */
    List<TempFile> selectByExample(TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_file
     *
     * @mbg.generated
     */
    TempFile selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_file
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") TempFile row, @Param("example") TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_file
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("row") TempFile row, @Param("example") TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_file
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") TempFile row, @Param("example") TempFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TempFile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(TempFile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_file
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TempFile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_file
     *
     * @mbg.generated
     */
    int merge(TempFile row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_temp_file
     *
     * @mbg.generated
     */
    void truncate();
}