package jp.co.stnet.cms.base.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.base.domain.model.mbg.Variable;
import jp.co.stnet.cms.base.domain.model.mbg.VariableExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface VariableMapper extends jp.co.stnet.cms.base.infrastructure.mapper.VersionMapperInterface<Variable, VariableExample, Integer> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    @Override
    long countByExample(VariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    @Override
    int deleteByExample(VariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    @Override
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    @Override
    int insert(Variable row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    @Override
    int insertSelective(Variable row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    List<Variable> selectByExampleWithRowbounds(VariableExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    @Override
    List<Variable> selectByExample(VariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    @Override
    Variable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    @Override
    int updateByExampleSelective(@Param("row") Variable row, @Param("example") VariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    @Override
    int updateByExample(@Param("row") Variable row, @Param("example") VariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersionSelective(Variable row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    @Override
    int updateByPrimaryKeySelective(Variable row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersion(Variable row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table variable
     *
     * @mbg.generated
     */
    @Override
    int updateByPrimaryKey(Variable row);
}