package jp.co.stnet.cms.base.infrastructure.mapper.mbg;

import java.util.List;
import jp.co.stnet.cms.base.domain.model.mbg.Variable;
import jp.co.stnet.cms.base.domain.model.mbg.VariableExample;
import jp.co.stnet.cms.base.infrastructure.mapper.VersionMapperInterface;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

@Mapper
public interface VariableMapper extends VersionMapperInterface<Variable, VariableExample, Long> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_variable
     *
     * @mbg.generated
     */
    long countByExample(VariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_variable
     *
     * @mbg.generated
     */
    int deleteByExample(VariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_variable
     *
     * @mbg.generated
     */
    int deleteByPrimaryKeyAndVersion(@Param("id") Long id, @Param("version") Long version);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_variable
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_variable
     *
     * @mbg.generated
     */
    int insert(Variable row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_variable
     *
     * @mbg.generated
     */
    int insertSelective(Variable row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_variable
     *
     * @mbg.generated
     */
    List<Variable> selectByExampleWithRowbounds(VariableExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_variable
     *
     * @mbg.generated
     */
    List<Variable> selectByExample(VariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_variable
     *
     * @mbg.generated
     */
    Variable selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_variable
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("row") Variable row, @Param("example") VariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_variable
     *
     * @mbg.generated
     */
    int updateByExample(@Param("row") Variable row, @Param("example") VariableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_variable
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersionSelective(Variable row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_variable
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Variable row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_variable
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyAndVersion(Variable row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_variable
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Variable row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_variable
     *
     * @mbg.generated
     */
    int merge(Variable row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_variable
     *
     * @mbg.generated
     */
    void truncate();
}